package generator

import (
	"bytes"
	"fmt"
	"go/format"

	di "github.com/asp24/gendi"
)

type emitter struct {
	options EmitOptions
}

func newEmitter(options EmitOptions) *emitter {
	return &emitter{options: options}
}

func (e *emitter) assembleOutput(body *bytes.Buffer, importManager *ImportManager) []byte {
	out := &bytes.Buffer{}

	// Build tags
	if e.options.BuildTags != "" {
		fmt.Fprintf(out, "//go:build %s\n", e.options.BuildTags)
		fmt.Fprintf(out, "// +build %s\n\n", e.options.BuildTags)
	}

	// Package and imports
	fmt.Fprintln(out, "// Code generated by gendi; DO NOT EDIT.")
	fmt.Fprintf(out, "package %s\n\n", e.options.Package)

	extraImports := []string{"sync", "fmt", "github.com/asp24/gendi/parameters"}
	out.WriteString(importManager.renderImports(extraImports))
	out.Write(body.Bytes())

	return out.Bytes()
}

func (e *emitter) emit(cfg *di.Config, ctx *genContext) ([]byte, error) {
	identGenerator := NewIdentGenerator()
	getterRegistry := NewGetterRegistry(identGenerator)
	importManager := NewImportManager(e.options.OutputPkgPath)
	inliner := NewInlinerComposite(
		NewInlinerMakeSlice(importManager),
		NewInlinerMakeChan(importManager),
	)

	body := &bytes.Buffer{}

	pRenderer := NewParametersRenderer(importManager)
	if err := pRenderer.Render(cfg.Parameters, e.options.Container, body); err != nil {
		return nil, err
	}

	cRenderer := NewContainerRenderer(importManager, identGenerator, getterRegistry, inliner, e.options.Container)
	if err := cRenderer.Render(cfg, ctx, body); err != nil {
		return nil, err
	}

	code := e.assembleOutput(body, cRenderer.importManager)
	formatted, err := format.Source(code)
	if err != nil {
		return nil, fmt.Errorf("format generated code: %w", err)
	}

	return formatted, nil
}
