package generator

import (
	"bytes"
	"fmt"
	"go/format"
	"sort"
	"strconv"

	di "github.com/asp24/gendi"
	"github.com/asp24/gendi/ir"
)

type Generator struct {
	cfg     *di.Config
	options Options
}

func New(cfg *di.Config, opts Options) *Generator {
	return &Generator{cfg: cfg, options: opts}
}

func collectTagGetterNames(ctx *genContext) []string {
	tagNames := map[string]bool{}
	for name, tag := range ctx.tags {
		if tag != nil && tag.Public {
			tagNames[name] = true
		}
	}
	for _, svc := range ctx.services {
		if svc == nil {
			continue
		}
		for _, arg := range svc.constructor.argDefs {
			if arg.Kind == ir.TaggedArg && arg.Tag != nil {
				tagNames[arg.Tag.Name] = true
			}
		}
	}
	items := make([]string, 0, len(tagNames))
	for name := range tagNames {
		items = append(items, name)
	}
	sort.Strings(items)
	return items
}

func (g *Generator) render(ctx *genContext, rnd *Renderer) ([]byte, error) {
	// Assign getter names and populate serviceDef fields
	tagGetterNames := collectTagGetterNames(ctx)
	rnd.assignNames(ctx, tagGetterNames)

	body := &bytes.Buffer{}
	hasParams := len(g.cfg.Parameters) > 0
	reservedAliases := []string{"sync", "fmt"}
	if hasParams {
		reservedAliases = append(reservedAliases, "parameters")
	}
	rnd.imports.ReserveAliases(reservedAliases...)

	// Render main code sections
	if err := g.renderParameters(body, hasParams); err != nil {
		return nil, err
	}
	if err := rnd.renderContainerStruct(body, ctx, hasParams); err != nil {
		return nil, err
	}
	if err := rnd.renderBuildFunctions(body, ctx); err != nil {
		return nil, err
	}
	if err := rnd.renderGetterFunctions(body, ctx, tagGetterNames); err != nil {
		return nil, err
	}

	// Assemble final output with header
	return g.assembleOutput(body, rnd, hasParams), nil
}

func (g *Generator) assembleOutput(body *bytes.Buffer, rnd *Renderer, hasParams bool) []byte {
	out := &bytes.Buffer{}

	// Build tags
	if g.options.BuildTags != "" {
		fmt.Fprintf(out, "//go:build %s\n", g.options.BuildTags)
		fmt.Fprintf(out, "// +build %s\n\n", g.options.BuildTags)
	}

	// Package and imports
	fmt.Fprintln(out, "// Code generated by di-gen; DO NOT EDIT.")
	fmt.Fprintf(out, "package %s\n\n", g.options.Package)

	extraImports := []string{"sync", "fmt"}
	if hasParams {
		extraImports = append(extraImports, "github.com/asp24/gendi/parameters")
	}
	out.WriteString(rnd.imports.renderImports(extraImports))
	out.Write(body.Bytes())

	return out.Bytes()
}

func (g *Generator) renderParameters(b *bytes.Buffer, hasParams bool) error {
	if !hasParams {
		return nil
	}

	keys := make([]string, 0, len(g.cfg.Parameters))
	for k := range g.cfg.Parameters {
		keys = append(keys, k)
	}
	sort.Strings(keys)

	b.WriteString("var DefaultParameters = parameters.NewProviderMap(map[string]any{\n")
	for _, name := range keys {
		param := g.cfg.Parameters[name]
		lit, err := literalExpr(param.Value)
		if err != nil {
			return fmt.Errorf("parameter %q: %w", name, err)
		}
		fmt.Fprintf(b, "\t%q: %s,\n", name, lit)
	}
	b.WriteString("})\n\n")
	return nil
}

func literalExpr(lit di.Literal) (string, error) {
	switch lit.Kind {
	case di.LiteralString:
		return strconv.Quote(lit.String()), nil
	case di.LiteralInt:
		return fmt.Sprintf("%d", lit.Int()), nil
	case di.LiteralFloat:
		return fmt.Sprintf("%v", lit.Float()), nil
	case di.LiteralBool:
		return fmt.Sprintf("%t", lit.Bool()), nil
	case di.LiteralNull:
		return "nil", nil
	default:
		return "", fmt.Errorf("unsupported literal kind %d", lit.Kind)
	}
}

// Generate produces the container code.
// Options must be finalized before calling New() (via Options.Finalize()).
// Config should already have passes applied (via di.ApplyPasses()).
func (g *Generator) Generate() ([]byte, error) {
	// Build context
	builder := NewContextBuilder(g.cfg, g.options)

	ctx, err := builder.Build()
	if err != nil {
		return nil, err
	}

	ident := &identGenerator{}
	getters := newGetterRegistry(ident)
	imports := NewImportManager(g.options.OutputPkgPath)
	rnd := NewRenderer(imports, ident, getters, g.options.Container)

	// Render code
	code, err := g.render(ctx, rnd)
	if err != nil {
		return nil, err
	}

	// Format
	formatted, err := format.Source(code)
	if err != nil {
		return nil, fmt.Errorf("format generated code: %w", err)
	}
	return formatted, nil
}
