package generator

import (
	"bytes"
	"fmt"
	"go/format"

	di "github.com/asp24/gendi"
	"github.com/asp24/gendi/ir"
	"github.com/asp24/gendi/typeres"
)

type Generator struct {
	options Options
}

func New(opts Options) *Generator {
	return &Generator{options: opts}
}

func (g *Generator) createTypeResolver(cfg *di.Config) (*typeres.Resolver, error) {
	paths, err := collectPackagePaths(cfg)
	if err != nil {
		return nil, err
	}

	result := typeres.NewResolver(g.options.ModuleRoot)

	if err := result.LoadPackages(paths); err != nil {
		return nil, err
	}

	return result, nil
}

func (g *Generator) assembleOutput(body *bytes.Buffer, importManager *ImportManager) []byte {
	out := &bytes.Buffer{}

	// Build tags
	if g.options.BuildTags != "" {
		fmt.Fprintf(out, "//go:build %s\n", g.options.BuildTags)
		fmt.Fprintf(out, "// +build %s\n\n", g.options.BuildTags)
	}

	// Package and imports
	fmt.Fprintln(out, "// Code generated by gendi; DO NOT EDIT.")
	fmt.Fprintf(out, "package %s\n\n", g.options.Package)

	extraImports := []string{"sync", "fmt", "github.com/asp24/gendi/parameters"}
	out.WriteString(importManager.renderImports(extraImports))
	out.Write(body.Bytes())

	return out.Bytes()
}

// Generate produces the container code.
// Options must be finalized before calling New() (via Options.Finalize()).
// Internal passes are applied automatically
func (g *Generator) Generate(cfg *di.Config) ([]byte, error) {
	// Apply internal passes (idempotent - decorators already expanded will be skipped)
	cfg, err := di.ApplyInternalPasses(cfg)
	if err != nil {
		return nil, err
	}

	typeResolver, err := g.createTypeResolver(cfg)
	if err != nil {
		return nil, err
	}

	// di.Config -> IR
	irBuilder := ir.NewBuilder(typeResolver)
	irContainer, err := irBuilder.Build(cfg)
	if err != nil {
		return nil, err
	}

	// IR -> getContext
	irConverter := NewIRConverter(typeResolver, g.options)
	ctx, err := irConverter.Convert(irContainer, cfg)
	if err != nil {
		return nil, err
	}

	identGenerator := NewIdentGenerator()
	getterRegistry := NewGetterRegistry(identGenerator)
	importManager := NewImportManager(g.options.OutputPkgPath)

	body := &bytes.Buffer{}
	// Render
	pRenderer := NewParametersRenderer(importManager)
	if err := pRenderer.Render(cfg.Parameters, body); err != nil {
		return nil, err
	}

	cRenderer := NewContainerRenderer(importManager, identGenerator, getterRegistry, g.options.Container)
	if err := cRenderer.Render(cfg, ctx, body); err != nil {
		return nil, err
	}

	code := g.assembleOutput(body, cRenderer.importManager)

	// Format
	formatted, err := format.Source(code)
	if err != nil {
		return nil, fmt.Errorf("format generated code: %w", err)
	}

	return formatted, nil
}
