package generator

import (
	"bytes"
	"fmt"
	"go/format"

	di "github.com/asp24/gendi"
	"github.com/asp24/gendi/ir"
	"github.com/asp24/gendi/typeres"
)

type Generator struct {
	cfg     *di.Config
	options Options
}

func New(cfg *di.Config, opts Options) *Generator {
	return &Generator{cfg: cfg, options: opts}
}

func (g *Generator) render(ctx *genContext, cRenderer *ContainerRenderer) ([]byte, error) {
	body := &bytes.Buffer{}

	// Render main code sections
	if err := (&RendererParameters{importManager: cRenderer.imports}).Render(g.cfg.Parameters, body); err != nil {
		return nil, err
	}

	if err := cRenderer.Render(g.cfg, ctx, body); err != nil {
		return nil, err
	}

	// Assemble final output with header
	return g.assembleOutput(body, cRenderer), nil
}

func (g *Generator) assembleOutput(body *bytes.Buffer, cRenderer *ContainerRenderer) []byte {
	out := &bytes.Buffer{}

	// Build tags
	if g.options.BuildTags != "" {
		fmt.Fprintf(out, "//go:build %s\n", g.options.BuildTags)
		fmt.Fprintf(out, "// +build %s\n\n", g.options.BuildTags)
	}

	// Package and imports
	fmt.Fprintln(out, "// Code generated by di-gen; DO NOT EDIT.")
	fmt.Fprintf(out, "package %s\n\n", g.options.Package)

	extraImports := []string{"sync", "fmt", "github.com/asp24/gendi/parameters"}
	out.WriteString(cRenderer.imports.renderImports(extraImports))
	out.Write(body.Bytes())

	return out.Bytes()
}

func (g *Generator) createTypeResolver(cfg *di.Config) (*typeres.Resolver, error) {
	paths, err := collectPackagePaths(cfg)
	if err != nil {
		return nil, err
	}

	result := typeres.NewResolver(g.options.ModuleRoot)

	if err := result.LoadPackages(paths); err != nil {
		return nil, err
	}

	return result, nil
}

// Generate produces the container code.
// Options must be finalized before calling New() (via Options.Finalize()).
// Config should already have passes applied (via di.ApplyPasses()).
func (g *Generator) Generate() ([]byte, error) {
	typeResolver, err := g.createTypeResolver(g.cfg)
	if err != nil {
		return nil, err
	}

	// di.Config -> IR
	irBuilder := ir.NewBuilder(typeResolver)
	irContainer, err := irBuilder.Build(g.cfg)
	if err != nil {
		return nil, err
	}

	// IR -> getContext
	irConverter := NewIRConverter(typeResolver, g.options)
	ctx, err := irConverter.Convert(irContainer, g.cfg)
	if err != nil {
		return nil, err
	}

	ident := &identGenerator{}
	getters := newGetterRegistry(ident)
	imports := NewImportManager(g.options.OutputPkgPath)
	cRenderer := NewContainerRenderer(imports, ident, getters, g.options.Container)

	// Render code
	code, err := g.render(ctx, cRenderer)
	if err != nil {
		return nil, err
	}

	// Format
	formatted, err := format.Source(code)
	if err != nil {
		return nil, fmt.Errorf("format generated code: %w", err)
	}

	return formatted, nil
}
