package generator

import (
	"bytes"
	"fmt"
	"go/types"
	"sort"
	"strconv"
	"strings"

	di "github.com/asp24/gendi"
	"github.com/asp24/gendi/ir"
)

func (g *Generator) render(ctx *genContext) ([]byte, error) {
	assignGetterNames(ctx)
	reachable := reachableServices(ctx)
	body := &bytes.Buffer{}

	// Parameters
	hasParams := len(g.cfg.Parameters) > 0
	if hasParams {
		keys := make([]string, 0, len(g.cfg.Parameters))
		for k := range g.cfg.Parameters {
			keys = append(keys, k)
		}
		sort.Strings(keys)
		body.WriteString("var DefaultParameters = parameters.NewProviderMap(map[string]any{\n")
		for _, name := range keys {
			param := g.cfg.Parameters[name]
			lit, err := literalExpr(param.Value)
			if err != nil {
				return nil, fmt.Errorf("parameter %q: %w", name, err)
			}
			fmt.Fprintf(body, "\t%q: %s,\n", name, lit)
		}
		body.WriteString("})\n\n")
	}

	// Container struct
	fmt.Fprintf(body, "type %s struct {\n", ctx.containerName)
	fmt.Fprintf(body, "\tmu sync.Mutex\n")
	if hasParams {
		fmt.Fprintf(body, "\tparams parameters.Provider\n")
	}
	for _, id := range ctx.orderedServiceIDs {
		svc := ctx.services[id]
		if !reachable[id] {
			continue
		}
		if svc.isDecorator && !decoratorNeedsPrivateGetter(ctx, svc) {
			continue
		}
		if !svc.shared {
			continue
		}
		getterType := getterType(svc, ctx.services, ctx.decoratorsByBase)
		isPtr := isNilablePointer(getterType)
		fmt.Fprintf(body, "\t%s %s\n", fieldIdent(id), ctx.imports.typeString(getterType))
		if !isPtr {
			fmt.Fprintf(body, "\t%sInit bool\n", fieldIdent(id))
		}
	}
	body.WriteString("}\n\n")
	if hasParams {
		fmt.Fprintf(body, "func New%s(params parameters.Provider) *%s {\n", ctx.containerName, ctx.containerName)
		fmt.Fprintf(body, "\tif params == nil {\n")
		fmt.Fprintf(body, "\t\tparams = DefaultParameters\n")
		fmt.Fprintf(body, "\t}\n")
		fmt.Fprintf(body, "\treturn &%s{params: params}\n", ctx.containerName)
		body.WriteString("}\n\n")
	}

	// Build functions and getters
	for _, id := range ctx.orderedServiceIDs {
		svc := ctx.services[id]
		if !reachable[id] {
			continue
		}
		if svc.aliasTarget != "" {
			continue
		}
		if svc.isDecorator {
			if err := renderDecoratorBuild(body, ctx, svc); err != nil {
				return nil, err
			}
			continue
		}
		if err := renderBuild(body, ctx, svc); err != nil {
			return nil, err
		}
	}
	for _, id := range ctx.orderedServiceIDs {
		svc := ctx.services[id]
		if !reachable[id] {
			continue
		}
		if svc.aliasTarget != "" {
			continue
		}
		if svc.isDecorator {
			if err := renderDecoratorChain(body, ctx, svc); err != nil {
				return nil, err
			}
		}
	}
	for _, id := range ctx.orderedServiceIDs {
		if !reachable[id] {
			continue
		}
		svc := ctx.services[id]
		if svc.isDecorator && !decoratorNeedsPrivateGetter(ctx, svc) {
			continue
		}
		if err := renderPrivateGetter(body, ctx, ctx.services[id]); err != nil {
			return nil, err
		}
	}
	for _, id := range ctx.orderedServiceIDs {
		svc := ctx.services[id]
		if !reachable[id] {
			continue
		}
		if !svc.public {
			continue
		}
		if err := renderGetter(body, ctx, svc); err != nil {
			return nil, err
		}
	}

	out := &bytes.Buffer{}
	if g.options.BuildTags != "" {
		fmt.Fprintf(out, "//go:build %s\n", g.options.BuildTags)
		fmt.Fprintf(out, "// +build %s\n\n", g.options.BuildTags)
	}
	fmt.Fprintln(out, "// Code generated by di-gen; DO NOT EDIT.")
	fmt.Fprintf(out, "package %s\n\n", g.options.Package)

	extraImports := []string{"sync", "fmt"}
	if hasParams {
		extraImports = append(extraImports, "github.com/asp24/gendi/parameters")
	}
	out.WriteString(ctx.imports.renderImports(extraImports))
	out.Write(body.Bytes())
	return out.Bytes(), nil
}

func renderBuild(b *bytes.Buffer, ctx *genContext, svc *serviceDef) error {
	name := buildName(svc)
	retType := ctx.imports.typeString(svc.typeName)
	returnsErr := buildNeedsErrorHandling(svc)
	fmt.Fprintf(b, "func (c *%s) %s() (%s, error) {\n", ctx.containerName, name, retType)
	if returnsErr {
		fmt.Fprintf(b, "\tvar zero %s\n", retType)
	}

	stmts, callExpr, err := constructorCall(ctx, svc, "", returnsErr)
	if err != nil {
		return err
	}
	for _, stmt := range stmts {
		fmt.Fprintf(b, "\t%s\n", stmt)
	}
	if svc.constructor.returnsError {
		fmt.Fprintf(b, "\tres, err := %s\n", callExpr)
		fmt.Fprintf(b, "\tif err != nil {\n\t\treturn zero, fmt.Errorf(\"service %%q constructor: %%w\", %q, err)\n\t}\n", svc.id)
		fmt.Fprintf(b, "\treturn res, nil\n")
	} else {
		fmt.Fprintf(b, "\treturn %s, nil\n", callExpr)
	}
	b.WriteString("}\n\n")
	return nil
}

func renderDecoratorBuild(b *bytes.Buffer, ctx *genContext, svc *serviceDef) error {
	name := decoratorBuildName(svc)
	retType := ctx.imports.typeString(svc.typeName)
	innerType := ctx.imports.typeString(serviceDeclaredType(ctx, ctx.services[svc.decorates]))
	returnsErr := buildNeedsErrorHandling(svc)
	fmt.Fprintf(b, "func (c *%s) %s(inner %s) (%s, error) {\n", ctx.containerName, name, innerType, retType)
	if returnsErr {
		fmt.Fprintf(b, "\tvar zero %s\n", retType)
	}

	stmts, callExpr, err := constructorCall(ctx, svc, "inner", returnsErr)
	if err != nil {
		return err
	}
	for _, stmt := range stmts {
		fmt.Fprintf(b, "\t%s\n", stmt)
	}
	if svc.constructor.returnsError {
		fmt.Fprintf(b, "\tres, err := %s\n", callExpr)
		fmt.Fprintf(b, "\tif err != nil {\n\t\treturn zero, fmt.Errorf(\"service %%q constructor: %%w\", %q, err)\n\t}\n", svc.id)
		fmt.Fprintf(b, "\treturn res, nil\n")
	} else {
		fmt.Fprintf(b, "\treturn %s, nil\n", callExpr)
	}
	b.WriteString("}\n\n")
	return nil
}

func renderDecoratorChain(b *bytes.Buffer, ctx *genContext, svc *serviceDef) error {
	baseID := svc.decorates
	decs := ctx.decoratorsByBase[baseID]
	if len(decs) == 0 {
		return nil
	}
	chainName := chainBuildName(svc)
	retType := ctx.imports.typeString(svc.typeName)
	fmt.Fprintf(b, "func (c *%s) %s() (%s, error) {\n", ctx.containerName, chainName, retType)
	fmt.Fprintf(b, "\tvar zero %s\n", retType)

	baseSvc := ctx.services[baseID]
	baseBuild := buildName(baseSvc)
	innerVar := "inner0"
	fmt.Fprintf(b, "\t%s, err := c.%s()\n", innerVar, baseBuild)
	fmt.Fprintf(b, "\tif err != nil {\n\t\treturn zero, fmt.Errorf(\"service %%q base %%q: %%w\", %q, %q, err)\n\t}\n", svc.id, baseID)

	for i, d := range decs {
		nextVar := fmt.Sprintf("inner%d", i+1)
		call := fmt.Sprintf("c.%s(%s)", decoratorBuildName(d), innerVar)
		fmt.Fprintf(b, "\t%s, err := %s\n", nextVar, call)
		fmt.Fprintf(b, "\tif err != nil {\n\t\treturn zero, fmt.Errorf(\"service %%q decorator %%q: %%w\", %q, %q, err)\n\t}\n", svc.id, d.id)
		if d.id == svc.id {
			fmt.Fprintf(b, "\treturn %s, nil\n", nextVar)
			b.WriteString("}\n\n")
			return nil
		}
		innerVar = nextVar
	}

	fmt.Fprintf(b, "\treturn %s, nil\n", innerVar)
	b.WriteString("}\n\n")
	return nil
}

func renderPrivateGetter(b *bytes.Buffer, ctx *genContext, svc *serviceDef) error {
	getter := svc.privateGetterName
	resType := getterType(svc, ctx.services, ctx.decoratorsByBase)
	getterType := ctx.imports.typeString(resType)
	isPtr := isNilablePointer(resType)
	fmt.Fprintf(b, "func (c *%s) %s() (%s, error) {\n", ctx.containerName, getter, getterType)

	if svc.aliasTarget != "" {
		target := ctx.services[svc.aliasTarget]
		if target == nil {
			return fmt.Errorf("unknown alias target %q", svc.aliasTarget)
		}
		fmt.Fprintf(b, "\treturn c.%s()\n", target.privateGetterName)
		b.WriteString("}\n\n")
		return nil
	}
	fmt.Fprintf(b, "\tvar zero %s\n", getterType)

	if svc.shared {
		if isPtr {
			fmt.Fprintf(b, "\tif c.%s != nil {\n\t\treturn c.%s, nil\n\t}\n", fieldIdent(svc.id), fieldIdent(svc.id))
			fmt.Fprintf(b, "\tres, err := %s\n", getterBuildExpr(ctx, svc))
			fmt.Fprintf(b, "\tif err != nil {\n")
			fmt.Fprintf(b, "\t\treturn zero, err\n\t}\n")
			fmt.Fprintf(b, "\tc.%s = res\n", fieldIdent(svc.id))
			fmt.Fprintf(b, "\treturn res, nil\n")
		} else {
			fmt.Fprintf(b, "\tif c.%sInit {\n", fieldIdent(svc.id))
			fmt.Fprintf(b, "\t\treturn c.%s, nil\n", fieldIdent(svc.id))
			fmt.Fprintf(b, "\t}\n")
			fmt.Fprintf(b, "\tres, err := %s\n", getterBuildExpr(ctx, svc))
			fmt.Fprintf(b, "\tif err != nil {\n")
			fmt.Fprintf(b, "\t\treturn zero, err\n\t}\n")
			fmt.Fprintf(b, "\tc.%s = res\n", fieldIdent(svc.id))
			fmt.Fprintf(b, "\tc.%sInit = true\n", fieldIdent(svc.id))
			fmt.Fprintf(b, "\treturn res, nil\n")
		}
	} else {
		fmt.Fprintf(b, "\tres, err := %s\n", getterBuildExpr(ctx, svc))
		fmt.Fprintf(b, "\tif err != nil {\n\t\treturn zero, err\n\t}\n")
		fmt.Fprintf(b, "\treturn res, nil\n")
	}
	b.WriteString("}\n\n")
	return nil
}

func renderGetter(b *bytes.Buffer, ctx *genContext, svc *serviceDef) error {
	getter := svc.getterName
	fmt.Fprintf(b, "func (c *%s) %s() (%s, error) {\n", ctx.containerName, getter, ctx.imports.typeString(getterType(svc, ctx.services, ctx.decoratorsByBase)))
	fmt.Fprintf(b, "\tc.mu.Lock()\n")
	fmt.Fprintf(b, "\tdefer c.mu.Unlock()\n")
	fmt.Fprintf(b, "\treturn c.%s()\n", svc.privateGetterName)
	b.WriteString("}\n\n")
	return nil
}

func constructorCall(ctx *genContext, svc *serviceDef, innerVar string, returnsErr bool) ([]string, string, error) {
	stmts := []string{}
	args := []string{}
	for i, arg := range svc.constructor.argDefs {
		var paramType types.Type = types.Typ[types.Invalid]
		if i < len(svc.constructor.params) {
			paramType = svc.constructor.params[i]
		}
		argExpr, argStmts, err := buildArg(ctx, svc, arg, innerVar, returnsErr, i, paramType)
		if err != nil {
			return nil, "", err
		}
		stmts = append(stmts, argStmts...)
		args = append(args, argExpr)
	}

	var call string
	if svc.constructor.kind == "func" {
		call = fmt.Sprintf("%s(%s)", ctx.imports.funcName(svc.constructor.funcObj), strings.Join(args, ", "))
	} else {
		recv := svc.constructor.methodRecvID
		recvGetter := ctx.services[recv].privateGetterName
		recvExpr := fmt.Sprintf("c.%s()", recvGetter)
		recvVar := varIdent("recv", svc.id)
		if returnsErr {
			stmts = append(stmts, fmt.Sprintf("%s, err := %s", recvVar, recvExpr))
			stmts = append(stmts, fmt.Sprintf("if err != nil { return zero, fmt.Errorf(\"service %%q receiver %%q: %%w\", %q, %q, err) }", svc.id, recv))
		} else {
			stmts = append(stmts, fmt.Sprintf("%s, _ := %s", recvVar, recvExpr))
		}
		recvExpr = recvVar
		call = fmt.Sprintf("%s.%s(%s)", recvExpr, svc.constructor.methodObj.Name(), strings.Join(args, ", "))
	}
	return stmts, call, nil
}

func buildArg(ctx *genContext, svc *serviceDef, arg *ir.Argument, innerVar string, returnsErr bool, argIndex int, paramType types.Type) (string, []string, error) {
	switch arg.Kind {
	case ir.ServiceRefArg:
		dep := ctx.services[arg.Service.ID]
		if dep == nil {
			return "", nil, fmt.Errorf("unknown service %q", arg.Service.ID)
		}
		call := fmt.Sprintf("c.%s()", dep.privateGetterName)
		depVar := varIdent("dep", dep.id)
		if returnsErr {
			stmts := []string{
				fmt.Sprintf("%s, err := %s", depVar, call),
				fmt.Sprintf("if err != nil { return zero, fmt.Errorf(\"service %%q arg[%%d]: %%w\", %q, %d, err) }", svc.id, argIndex),
			}
			return depVar, stmts, nil
		}
		stmts := []string{fmt.Sprintf("%s, _ := %s", depVar, call)}
		return depVar, stmts, nil
	case ir.InnerArg:
		if innerVar == "" {
			return "", nil, fmt.Errorf("@.inner used outside decorator")
		}
		return innerVar, nil, nil
	case ir.ParamRefArg:
		method := ctx.paramGetters[arg.Parameter.Name]
		if method == "" {
			return "", nil, fmt.Errorf("unknown parameter %q", arg.Parameter.Name)
		}
		paramVar := varIdent("param", arg.Parameter.Name)
		stmts := []string{
			fmt.Sprintf("if c.params == nil { return zero, fmt.Errorf(\"service %%q arg[%%d] param %%q: parameters provider is nil\", %q, %d, %q) }", svc.id, argIndex, arg.Parameter.Name),
			fmt.Sprintf("%s, err := c.params.%s(%q)", paramVar, method, arg.Parameter.Name),
			fmt.Sprintf("if err != nil { return zero, fmt.Errorf(\"service %%q arg[%%d] param %%q: %%w\", %q, %d, %q, err) }", svc.id, argIndex, arg.Parameter.Name),
		}
		return paramVar, stmts, nil
	case ir.TaggedArg:
		values := taggedServices(ctx, arg.Tag.Name)
		items := make([]string, 0, len(values))
		stmts := []string{}
		for _, dep := range values {
			call := fmt.Sprintf("c.%s()", dep.privateGetterName)
			varName := varIdent("tag", dep.id)
			if returnsErr {
				stmts = append(stmts, fmt.Sprintf("%s, err := %s", varName, call))
				stmts = append(stmts, fmt.Sprintf("if err != nil { return zero, fmt.Errorf(\"service %%q arg[%%d] tag %%q: %%w\", %q, %d, %q, err) }", svc.id, argIndex, arg.Tag.Name))
				items = append(items, varName)
			} else {
				stmts = append(stmts, fmt.Sprintf("%s, _ := %s", varName, call))
				items = append(items, varName)
			}
		}
		sliceExpr := "[]" + ctx.imports.typeString(tagElementType(ctx, arg.Tag.Name)) + "{" + strings.Join(items, ", ") + "}"
		return sliceExpr, stmts, nil
	default:
		if isTimeDuration(paramType) {
			nanos, err := durationLiteralValue(arg.Literal)
			if err != nil {
				return "", nil, err
			}
			return fmt.Sprintf("%d", nanos), nil, nil
		}
		lit, err := literalValueExpr(arg.Literal)
		if err != nil {
			return "", nil, err
		}
		return lit, nil, nil
	}
}

func taggedServices(ctx *genContext, tag string) []*serviceDef {
	var items []*serviceDef
	for id, svc := range ctx.services {
		for _, t := range svc.cfg.Tags {
			if t.Name == tag {
				items = append(items, ctx.services[id])
			}
		}
	}
	sortByPriority := false
	if def, ok := ctx.cfg.Tags[tag]; ok && def.SortBy == "priority" {
		sortByPriority = true
	}
	if sortByPriority {
		sort.Slice(items, func(i, j int) bool {
			pi, pj := tagPriority(items[i], tag), tagPriority(items[j], tag)
			if pi == pj {
				return items[i].id < items[j].id
			}
			return pi > pj
		})
	} else {
		sort.Slice(items, func(i, j int) bool {
			return items[i].id < items[j].id
		})
	}
	return items
}

func tagPriority(svc *serviceDef, tag string) int {
	for _, t := range svc.cfg.Tags {
		if t.Name != tag {
			continue
		}
		if v, ok := t.Attributes["priority"]; ok {
			switch val := v.(type) {
			case int:
				return val
			case int64:
				return int(val)
			case float64:
				return int(val)
			case string:
				if parsed, err := strconv.Atoi(val); err == nil {
					return parsed
				}
			}
		}
	}
	return 0
}

func tagElementType(ctx *genContext, tag string) types.Type {
	if t, ok := ctx.cfg.Tags[tag]; ok {
		typeName, _ := ctx.loader.LookupType(t.ElementType)
		return typeName
	}
	return types.Typ[types.Invalid]
}

func assignGetterNames(ctx *genContext) {
	used := map[string]bool{}
	for _, id := range ctx.orderedServiceIDs {
		if ctx.services[id].public {
			base := "Get" + toCamel(id)
			name := base
			if used[name] {
				for i := 2; ; i++ {
					candidate := fmt.Sprintf("%s%d", base, i)
					if !used[candidate] {
						name = candidate
						break
					}
				}
			}
			used[name] = true
			ctx.services[id].getterName = name
		}
	}
	privateUsed := map[string]bool{}
	for _, id := range ctx.orderedServiceIDs {
		base := "get" + toCamel(id)
		name := base
		if privateUsed[name] {
			for i := 2; ; i++ {
				candidate := fmt.Sprintf("%s%d", base, i)
				if !privateUsed[candidate] {
					name = candidate
					break
				}
			}
		}
		privateUsed[name] = true
		ctx.services[id].privateGetterName = name
	}
}

func toCamel(id string) string {
	parts := strings.FieldsFunc(id, func(r rune) bool {
		return !(r >= 'a' && r <= 'z' || r >= 'A' && r <= 'Z' || r >= '0' && r <= '9')
	})
	for i, p := range parts {
		if p == "" {
			continue
		}
		parts[i] = strings.ToUpper(p[:1]) + p[1:]
	}
	if len(parts) == 0 {
		return "Service"
	}
	return strings.Join(parts, "")
}

func fieldIdent(id string) string {
	return "svc_" + sanitizeIdent(id)
}

func paramIdent(name string) string {
	return "param_" + sanitizeIdent(name)
}

func varIdent(prefix, id string) string {
	return prefix + "_" + sanitizeIdent(id)
}

func sanitizeIdent(id string) string {
	var b strings.Builder
	for _, r := range id {
		if (r >= 'a' && r <= 'z') || (r >= 'A' && r <= 'Z') || (r >= '0' && r <= '9') {
			b.WriteRune(r)
		} else {
			b.WriteRune('_')
		}
	}
	if b.Len() == 0 {
		return "id"
	}
	return b.String()
}

func buildName(svc *serviceDef) string {
	return "build" + toCamel(svc.id)
}

func decoratorBuildName(svc *serviceDef) string {
	return "build" + toCamel(svc.id) + "Decorator"
}

func chainBuildName(svc *serviceDef) string {
	return "buildDecorated" + toCamel(svc.id)
}

func getterBuildExpr(ctx *genContext, svc *serviceDef) string {
	if svc.isDecorator {
		return "c." + chainBuildName(svc) + "()"
	}
	if decs := ctx.decoratorsByBase[svc.id]; len(decs) > 0 {
		outer := decs[len(decs)-1]
		return "c." + chainBuildName(outer) + "()"
	}
	return "c." + buildName(svc) + "()"
}

func literalExpr(lit di.Literal) (string, error) {
	switch lit.Kind {
	case di.LiteralString:
		return strconv.Quote(lit.String()), nil
	case di.LiteralInt:
		return fmt.Sprintf("%d", lit.Int()), nil
	case di.LiteralFloat:
		return fmt.Sprintf("%v", lit.Float()), nil
	case di.LiteralBool:
		return fmt.Sprintf("%t", lit.Bool()), nil
	case di.LiteralNull:
		return "nil", nil
	default:
		return "", fmt.Errorf("unsupported literal kind %d", lit.Kind)
	}
}

func isNilablePointer(t types.Type) bool {
	switch tt := t.(type) {
	case *types.Pointer:
		return true
	case *types.Named:
		return isNilablePointer(tt.Underlying())
	default:
		return false
	}
}

func buildNeedsErrorHandling(svc *serviceDef) bool {
	if svc.constructor.returnsError || svc.constructor.kind == "method" {
		return true
	}
	for _, arg := range svc.constructor.argDefs {
		switch arg.Kind {
		case ir.ServiceRefArg, ir.TaggedArg, ir.ParamRefArg:
			return true
		}
	}
	return false
}

func serviceDeclaredType(ctx *genContext, svc *serviceDef) types.Type {
	if svc == nil {
		return types.Typ[types.Invalid]
	}
	if svc.cfg.Type == "" {
		return svc.typeName
	}
	declType, err := ctx.loader.LookupType(svc.cfg.Type)
	if err != nil {
		return svc.typeName
	}
	return declType
}

func reachableServices(ctx *genContext) map[string]bool {
	reachable := map[string]bool{}
	queue := []string{}
	for id, svc := range ctx.services {
		if svc.public {
			reachable[id] = true
			queue = append(queue, id)
		}
	}

	for len(queue) > 0 {
		id := queue[0]
		queue = queue[1:]
		svc := ctx.services[id]
		if svc == nil {
			continue
		}

		add := func(dep string) {
			if dep == "" || reachable[dep] {
				return
			}
			reachable[dep] = true
			queue = append(queue, dep)
		}

		if svc.constructor.kind == "method" {
			add(svc.constructor.methodRecvID)
		}
		if svc.aliasTarget != "" {
			add(svc.aliasTarget)
		}
		for _, arg := range svc.constructor.argDefs {
			switch arg.Kind {
			case ir.ServiceRefArg:
				add(arg.Service.ID)
			case ir.InnerArg:
				add(svc.decorates)
			case ir.TaggedArg:
				for _, tagSvc := range arg.Tag.Services {
					add(tagSvc.ID)
				}
			}
		}

		if svc.decorates != "" {
			add(svc.decorates)
		}
		if decs := ctx.decoratorsByBase[id]; len(decs) > 0 {
			for _, d := range decs {
				add(d.id)
			}
		}
	}

	return reachable
}

func decoratorNeedsPrivateGetter(ctx *genContext, svc *serviceDef) bool {
	if !svc.isDecorator || svc.public {
		return true
	}
	for _, other := range ctx.services {
		if other == nil {
			continue
		}
		if other.aliasTarget == svc.id {
			return true
		}
		if other.constructor.kind == "method" && other.constructor.methodRecvID == svc.id {
			return true
		}
		for _, arg := range other.constructor.argDefs {
			switch arg.Kind {
			case ir.ServiceRefArg:
				if arg.Service.ID == svc.id {
					return true
				}
			case ir.TaggedArg:
				for _, t := range svc.cfg.Tags {
					if t.Name == arg.Tag.Name {
						return true
					}
				}
			}
		}
	}
	return false
}
