// Code generated by gendi; DO NOT EDIT.
package main

import (
	"fmt"
	"sync"

	"github.com/asp24/gendi/parameters"
)

type Container struct {
	mu               sync.Mutex
	params           parameters.Provider
	onMustCallFailed func(serviceName string, err error)
	svc_consumer     *Consumer
}

type ContainerOption func(*Container)

func WithContainerErrorHandler(handler func(serviceName string, err error)) ContainerOption {
	return func(c *Container) {
		c.onMustCallFailed = handler
	}
}

func NewContainer(params parameters.Provider, opts ...ContainerOption) *Container {
	if params == nil {
		params = parameters.ProviderNullInstance
	}
	c := &Container{
		params:           params,
		onMustCallFailed: func(string, error) {},
	}
	for _, opt := range opts {
		opt(c)
	}
	return c
}

func (c *Container) buildFooBar() (*A, error) {
	return NewA(), nil
}

func (c *Container) buildFooBar2() (*B, error) {
	return NewB(), nil
}

func (c *Container) buildConsumer() (*Consumer, error) {
	var zero *Consumer
	arg0_foo_bar, err := c.getFooBar()
	if err != nil {
		return zero, fmt.Errorf("service %q arg[%d]: %w", "consumer", '\x00', err)
	}
	arg1_foo_bar, err := c.getFooBar2()
	if err != nil {
		return zero, fmt.Errorf("service %q arg[%d]: %w", "consumer", '\x01', err)
	}
	return NewConsumer(arg0_foo_bar, arg1_foo_bar), nil
}

func (c *Container) getFooBar() (*A, error) {
	return c.buildFooBar()
}

func (c *Container) getFooBar2() (*B, error) {
	return c.buildFooBar2()
}

func (c *Container) getConsumer() (*Consumer, error) {
	if c.svc_consumer != nil {
		return c.svc_consumer, nil
	}
	res, err := c.buildConsumer()
	if err != nil {
		return nil, err
	}
	c.svc_consumer = res
	return res, nil
}

func (c *Container) GetConsumer() (*Consumer, error) {
	c.mu.Lock()
	defer c.mu.Unlock()
	return c.getConsumer()
}

func (c *Container) MustConsumer() *Consumer {
	res, err := c.GetConsumer()
	if err != nil {
		c.onMustCallFailed("consumer", err)
		panic(err)
	}
	return res
}
