// Code generated by gendi; DO NOT EDIT.
package di

import (
	"fmt"
	app "github.com/asp24/gendi/examples/spread/app"
	"github.com/asp24/gendi/parameters"
	"sync"
)

var DefaultContainerParameters = parameters.NewProviderMap(map[string]any{
	"server_prefix": "/api/v1",
})

type Container struct {
	mu                  sync.Mutex
	params              parameters.Provider
	onMustCallFailed    func(serviceName string, err error)
	svc_handler_admin   *app.AdminHandler
	svc_handler_api     *app.APIHandler
	svc_handler_home    *app.HomeHandler
	svc_server_prefixed *app.PrefixedServer
	svc_server_ref      *app.Server
	svc_server_tagged   *app.Server
}

type ContainerOption func(*Container)

func WithContainerErrorHandler(handler func(serviceName string, err error)) ContainerOption {
	return func(c *Container) {
		c.onMustCallFailed = handler
	}
}

func NewContainer(params parameters.Provider, opts ...ContainerOption) *Container {
	if params == nil {
		params = DefaultContainerParameters
	}
	c := &Container{
		params:           params,
		onMustCallFailed: func(string, error) {},
	}
	for _, opt := range opts {
		opt(c)
	}
	return c
}

func (c *Container) buildHandlerAdmin() (*app.AdminHandler, error) {
	return app.NewAdminHandler(), nil
}

func (c *Container) buildHandlerApi() (*app.APIHandler, error) {
	return app.NewAPIHandler(), nil
}

func (c *Container) buildHandlerHome() (*app.HomeHandler, error) {
	return app.NewHomeHandler(), nil
}

func (c *Container) buildTaggedWithHandler() ([]app.Handler, error) {
	var zero []app.Handler
	arg0_handler_api, err := c.getHandlerApi()
	if err != nil {
		return zero, fmt.Errorf("service %q arg[%d]: %w", "__tagged_with.handler", '\x00', err)
	}
	arg1_handler_home, err := c.getHandlerHome()
	if err != nil {
		return zero, fmt.Errorf("service %q arg[%d]: %w", "__tagged_with.handler", '\x01', err)
	}
	arg2_handler_admin, err := c.getHandlerAdmin()
	if err != nil {
		return zero, fmt.Errorf("service %q arg[%d]: %w", "__tagged_with.handler", '\x02', err)
	}
	return []app.Handler{arg0_handler_api, arg1_handler_home, arg2_handler_admin}, nil
}

func (c *Container) buildAllHandlers() ([]app.Handler, error) {
	var zero []app.Handler
	arg0_handler_home, err := c.getHandlerHome()
	if err != nil {
		return zero, fmt.Errorf("service %q arg[%d]: %w", "all_handlers", '\x00', err)
	}
	arg1_handler_api, err := c.getHandlerApi()
	if err != nil {
		return zero, fmt.Errorf("service %q arg[%d]: %w", "all_handlers", '\x01', err)
	}
	arg2_handler_admin, err := c.getHandlerAdmin()
	if err != nil {
		return zero, fmt.Errorf("service %q arg[%d]: %w", "all_handlers", '\x02', err)
	}
	return app.GetAllHandlers(arg0_handler_home, arg1_handler_api, arg2_handler_admin), nil
}

func (c *Container) buildServerPrefixed() (*app.PrefixedServer, error) {
	var zero *app.PrefixedServer
	param0_server_prefix, err := c.params.GetString("server_prefix")
	if err != nil {
		return zero, fmt.Errorf("service %q arg[%d] param %q: %w", "server.prefixed", '\x00', "server_prefix", err)
	}
	arg1___tagged_with_handler, err := c.getTaggedWithHandler()
	if err != nil {
		return zero, fmt.Errorf("service %q arg[%d]: %w", "server.prefixed", '\x01', err)
	}
	return app.NewPrefixedServer(param0_server_prefix, arg1___tagged_with_handler...), nil
}

func (c *Container) buildServerRef() (*app.Server, error) {
	var zero *app.Server
	arg0_all_handlers, err := c.getAllHandlers()
	if err != nil {
		return zero, fmt.Errorf("service %q arg[%d]: %w", "server.ref", '\x00', err)
	}
	return app.NewServer(arg0_all_handlers...), nil
}

func (c *Container) buildServerTagged() (*app.Server, error) {
	var zero *app.Server
	arg0___tagged_with_handler, err := c.getTaggedWithHandler()
	if err != nil {
		return zero, fmt.Errorf("service %q arg[%d]: %w", "server.tagged", '\x00', err)
	}
	return app.NewServer(arg0___tagged_with_handler...), nil
}

func (c *Container) getHandlerAdmin() (*app.AdminHandler, error) {
	if c.svc_handler_admin != nil {
		return c.svc_handler_admin, nil
	}
	res, err := c.buildHandlerAdmin()
	if err != nil {
		return nil, err
	}
	c.svc_handler_admin = res
	return res, nil
}

func (c *Container) getHandlerApi() (*app.APIHandler, error) {
	if c.svc_handler_api != nil {
		return c.svc_handler_api, nil
	}
	res, err := c.buildHandlerApi()
	if err != nil {
		return nil, err
	}
	c.svc_handler_api = res
	return res, nil
}

func (c *Container) getHandlerHome() (*app.HomeHandler, error) {
	if c.svc_handler_home != nil {
		return c.svc_handler_home, nil
	}
	res, err := c.buildHandlerHome()
	if err != nil {
		return nil, err
	}
	c.svc_handler_home = res
	return res, nil
}

func (c *Container) getTaggedWithHandler() ([]app.Handler, error) {
	return c.buildTaggedWithHandler()
}

func (c *Container) getAllHandlers() ([]app.Handler, error) {
	return c.buildAllHandlers()
}

func (c *Container) getServerPrefixed() (*app.PrefixedServer, error) {
	if c.svc_server_prefixed != nil {
		return c.svc_server_prefixed, nil
	}
	res, err := c.buildServerPrefixed()
	if err != nil {
		return nil, err
	}
	c.svc_server_prefixed = res
	return res, nil
}

func (c *Container) getServerRef() (*app.Server, error) {
	if c.svc_server_ref != nil {
		return c.svc_server_ref, nil
	}
	res, err := c.buildServerRef()
	if err != nil {
		return nil, err
	}
	c.svc_server_ref = res
	return res, nil
}

func (c *Container) getServerTagged() (*app.Server, error) {
	if c.svc_server_tagged != nil {
		return c.svc_server_tagged, nil
	}
	res, err := c.buildServerTagged()
	if err != nil {
		return nil, err
	}
	c.svc_server_tagged = res
	return res, nil
}

func (c *Container) GetServerPrefixed() (*app.PrefixedServer, error) {
	c.mu.Lock()
	defer c.mu.Unlock()
	return c.getServerPrefixed()
}

func (c *Container) MustServerPrefixed() *app.PrefixedServer {
	res, err := c.GetServerPrefixed()
	if err != nil {
		c.onMustCallFailed("server.prefixed", err)
		panic(err)
	}
	return res
}

func (c *Container) GetServerRef() (*app.Server, error) {
	c.mu.Lock()
	defer c.mu.Unlock()
	return c.getServerRef()
}

func (c *Container) MustServerRef() *app.Server {
	res, err := c.GetServerRef()
	if err != nil {
		c.onMustCallFailed("server.ref", err)
		panic(err)
	}
	return res
}

func (c *Container) GetServerTagged() (*app.Server, error) {
	c.mu.Lock()
	defer c.mu.Unlock()
	return c.getServerTagged()
}

func (c *Container) MustServerTagged() *app.Server {
	res, err := c.GetServerTagged()
	if err != nil {
		c.onMustCallFailed("server.tagged", err)
		panic(err)
	}
	return res
}
