// Code generated by di-gen; DO NOT EDIT.
package main

import (
	"fmt"
	app "github.com/asp24/gendi/examples/custom-pass/internal/app"
	"github.com/asp24/gendi/parameters"
	stdlib "github.com/asp24/gendi/stdlib"
	io "io"
	slog "log/slog"
	"sync"
)

var DefaultParameters = parameters.NewProviderMap(map[string]any{
	"db_dsn":                              "postgres://localhost/myapp",
	"stdlib.http.idle_conn_timeout":       "90s",
	"stdlib.http.max_idle_conns":          100,
	"stdlib.http.max_idle_conns_per_host": 10,
	"stdlib.http.timeout":                 "30s",
	"stdlib.slog.level":                   0,
})

type Container struct {
	mu                               sync.Mutex
	params                           parameters.Provider
	svc_product_handler              app.HTTPHandler
	svc_product_handlerInit          bool
	svc_product_repo                 *app.ProductRepoImpl
	svc_server                       *app.Server
	svc_stdlib_slog                  *slog.Logger
	svc_stdlib_slog_handler_text     slog.Handler
	svc_stdlib_slog_handler_textInit bool
	svc_user_handler                 app.HTTPHandler
	svc_user_handlerInit             bool
	svc_user_repo                    *app.UserRepoImpl
}

func NewContainer(params parameters.Provider) *Container {
	if params == nil {
		params = DefaultParameters
	}
	return &Container{params: params}
}

func (c *Container) buildProductHandler() (app.HTTPHandler, error) {
	var zero app.HTTPHandler
	dep_product_handler_logger, err := c.getProductHandlerLogger()
	if err != nil {
		return zero, fmt.Errorf("service %q arg[%d]: %w", "product.handler", '\x00', err)
	}
	dep_product_repo, err := c.getProductRepo()
	if err != nil {
		return zero, fmt.Errorf("service %q arg[%d]: %w", "product.handler", '\x01', err)
	}
	return app.NewProductHandler(dep_product_handler_logger, dep_product_repo), nil
}

func (c *Container) buildProductHandlerLogger() (*slog.Logger, error) {
	var zero *slog.Logger
	recv_product_handler_logger, err := c.getLogger()
	if err != nil {
		return zero, fmt.Errorf("service %q receiver %q: %w", "product.handler.logger", "logger", err)
	}
	return recv_product_handler_logger.With("channel", "product"), nil
}

func (c *Container) buildProductRepo() (*app.ProductRepoImpl, error) {
	var zero *app.ProductRepoImpl
	param_db_dsn, err := c.params.GetString("db_dsn")
	if err != nil {
		return zero, fmt.Errorf("service %q arg[%d] param %q: %w", "product.repo", '\x00', "db_dsn", err)
	}
	return app.NewProductRepository(param_db_dsn), nil
}

func (c *Container) buildServer() (*app.Server, error) {
	var zero *app.Server
	dep_server_logger, err := c.getServerLogger()
	if err != nil {
		return zero, fmt.Errorf("service %q arg[%d]: %w", "server", '\x00', err)
	}
	tagged1_http_handler, err := c.getTaggedWithHttpHandler()
	if err != nil {
		return zero, fmt.Errorf("service %q arg[%d] tag %q: %w", "server", '\x01', "http.handler", err)
	}
	return app.NewServer(dep_server_logger, tagged1_http_handler), nil
}

func (c *Container) buildServerLogger() (*slog.Logger, error) {
	var zero *slog.Logger
	recv_server_logger, err := c.getLogger()
	if err != nil {
		return zero, fmt.Errorf("service %q receiver %q: %w", "server.logger", "logger", err)
	}
	return recv_server_logger.With("channel", "http"), nil
}

func (c *Container) buildStdlibSlog() (*slog.Logger, error) {
	var zero *slog.Logger
	dep_stdlib_slog_handler, err := c.getStdlibSlogHandler()
	if err != nil {
		return zero, fmt.Errorf("service %q arg[%d]: %w", "stdlib.slog", '\x00', err)
	}
	return stdlib.NewSlogLogger(dep_stdlib_slog_handler), nil
}

func (c *Container) buildStdlibSlogHandlerText() (slog.Handler, error) {
	var zero slog.Handler
	dep_stdlib_slog_writer, err := c.getStdlibSlogWriter()
	if err != nil {
		return zero, fmt.Errorf("service %q arg[%d]: %w", "stdlib.slog.handler.text", '\x00', err)
	}
	param_stdlib_slog_level, err := c.params.GetInt("stdlib.slog.level")
	if err != nil {
		return zero, fmt.Errorf("service %q arg[%d] param %q: %w", "stdlib.slog.handler.text", '\x01', "stdlib.slog.level", err)
	}
	return stdlib.NewSlogTextHandler(dep_stdlib_slog_writer, slog.Level(param_stdlib_slog_level)), nil
}

func (c *Container) buildStdlibStderr() (io.Writer, error) {
	return stdlib.NewStderr(), nil
}

func (c *Container) buildUserHandler() (app.HTTPHandler, error) {
	var zero app.HTTPHandler
	dep_user_handler_logger, err := c.getUserHandlerLogger()
	if err != nil {
		return zero, fmt.Errorf("service %q arg[%d]: %w", "user.handler", '\x00', err)
	}
	dep_user_repo, err := c.getUserRepo()
	if err != nil {
		return zero, fmt.Errorf("service %q arg[%d]: %w", "user.handler", '\x01', err)
	}
	return app.NewUserHandler(dep_user_handler_logger, dep_user_repo), nil
}

func (c *Container) buildUserHandlerLogger() (*slog.Logger, error) {
	var zero *slog.Logger
	recv_user_handler_logger, err := c.getLogger()
	if err != nil {
		return zero, fmt.Errorf("service %q receiver %q: %w", "user.handler.logger", "logger", err)
	}
	return recv_user_handler_logger.With("channel", "user"), nil
}

func (c *Container) buildUserRepo() (*app.UserRepoImpl, error) {
	var zero *app.UserRepoImpl
	param_db_dsn, err := c.params.GetString("db_dsn")
	if err != nil {
		return zero, fmt.Errorf("service %q arg[%d] param %q: %w", "user.repo", '\x00', "db_dsn", err)
	}
	return app.NewUserRepository(param_db_dsn), nil
}

func (c *Container) getLogger() (*slog.Logger, error) {
	return c.getStdlibSlog()
}

func (c *Container) getProductHandler() (app.HTTPHandler, error) {
	var zero app.HTTPHandler
	if c.svc_product_handlerInit {
		return c.svc_product_handler, nil
	}
	res, err := c.buildProductHandler()
	if err != nil {
		return zero, err
	}
	c.svc_product_handler = res
	c.svc_product_handlerInit = true
	return res, nil
}

func (c *Container) getProductHandlerLogger() (*slog.Logger, error) {
	var zero *slog.Logger
	res, err := c.buildProductHandlerLogger()
	if err != nil {
		return zero, err
	}
	return res, nil
}

func (c *Container) getProductRepo() (*app.ProductRepoImpl, error) {
	var zero *app.ProductRepoImpl
	if c.svc_product_repo != nil {
		return c.svc_product_repo, nil
	}
	res, err := c.buildProductRepo()
	if err != nil {
		return zero, err
	}
	c.svc_product_repo = res
	return res, nil
}

func (c *Container) getServer() (*app.Server, error) {
	var zero *app.Server
	if c.svc_server != nil {
		return c.svc_server, nil
	}
	res, err := c.buildServer()
	if err != nil {
		return zero, err
	}
	c.svc_server = res
	return res, nil
}

func (c *Container) getServerLogger() (*slog.Logger, error) {
	var zero *slog.Logger
	res, err := c.buildServerLogger()
	if err != nil {
		return zero, err
	}
	return res, nil
}

func (c *Container) getStdlibSlog() (*slog.Logger, error) {
	var zero *slog.Logger
	if c.svc_stdlib_slog != nil {
		return c.svc_stdlib_slog, nil
	}
	res, err := c.buildStdlibSlog()
	if err != nil {
		return zero, err
	}
	c.svc_stdlib_slog = res
	return res, nil
}

func (c *Container) getStdlibSlogHandler() (slog.Handler, error) {
	return c.getStdlibSlogHandlerText()
}

func (c *Container) getStdlibSlogHandlerText() (slog.Handler, error) {
	var zero slog.Handler
	if c.svc_stdlib_slog_handler_textInit {
		return c.svc_stdlib_slog_handler_text, nil
	}
	res, err := c.buildStdlibSlogHandlerText()
	if err != nil {
		return zero, err
	}
	c.svc_stdlib_slog_handler_text = res
	c.svc_stdlib_slog_handler_textInit = true
	return res, nil
}

func (c *Container) getStdlibSlogWriter() (io.Writer, error) {
	return c.getStdlibStderr()
}

func (c *Container) getStdlibStderr() (io.Writer, error) {
	var zero io.Writer
	res, err := c.buildStdlibStderr()
	if err != nil {
		return zero, err
	}
	return res, nil
}

func (c *Container) getUserHandler() (app.HTTPHandler, error) {
	var zero app.HTTPHandler
	if c.svc_user_handlerInit {
		return c.svc_user_handler, nil
	}
	res, err := c.buildUserHandler()
	if err != nil {
		return zero, err
	}
	c.svc_user_handler = res
	c.svc_user_handlerInit = true
	return res, nil
}

func (c *Container) getUserHandlerLogger() (*slog.Logger, error) {
	var zero *slog.Logger
	res, err := c.buildUserHandlerLogger()
	if err != nil {
		return zero, err
	}
	return res, nil
}

func (c *Container) getUserRepo() (*app.UserRepoImpl, error) {
	var zero *app.UserRepoImpl
	if c.svc_user_repo != nil {
		return c.svc_user_repo, nil
	}
	res, err := c.buildUserRepo()
	if err != nil {
		return zero, err
	}
	c.svc_user_repo = res
	return res, nil
}

func (c *Container) getTaggedWithHttpHandler() ([]app.HTTPHandler, error) {
	items := make([]app.HTTPHandler, 0, 2)
	tagged_product_handler, err := c.getProductHandler()
	if err != nil {
		return nil, err
	}
	items = append(items, tagged_product_handler)
	tagged_user_handler, err := c.getUserHandler()
	if err != nil {
		return nil, err
	}
	items = append(items, tagged_user_handler)
	return items, nil
}

func (c *Container) GetServer() (*app.Server, error) {
	c.mu.Lock()
	defer c.mu.Unlock()
	return c.getServer()
}
