// Code generated by di-gen; DO NOT EDIT.
package main

import (
	"fmt"
	app "github.com/asp24/gendi/examples/custom-pass/internal/app"
	"github.com/asp24/gendi/parameters"
	slog "log/slog"
	"sync"
)

var DefaultParameters = parameters.NewProviderMap(map[string]any{
	"db_dsn": "postgres://localhost/myapp",
})

type Container struct {
	mu                         sync.Mutex
	params                     parameters.Provider
	svc_logger                 *slog.Logger
	svc_product_handler        app.HTTPHandler
	svc_product_handlerInit    bool
	svc_product_handler_logger *slog.Logger
	svc_product_repo           app.ProductRepository
	svc_product_repoInit       bool
	svc_server                 *app.Server
	svc_user_handler           app.HTTPHandler
	svc_user_handlerInit       bool
	svc_user_handler_logger    *slog.Logger
	svc_user_repo              app.UserRepository
	svc_user_repoInit          bool
}

func NewContainer(params parameters.Provider) *Container {
	if params == nil {
		params = DefaultParameters
	}
	return &Container{params: params}
}

func (c *Container) buildLogger() (*slog.Logger, error) {
	return createSLog(), nil
}

func (c *Container) buildProductHandler() (app.HTTPHandler, error) {
	var zero app.HTTPHandler
	dep_product_repo, err := c.getProductRepo()
	if err != nil {
		return zero, fmt.Errorf("service %q arg[%d]: %w", "product.handler", '\x00', err)
	}
	dep_product_handler_logger, err := c.getProductHandlerLogger()
	if err != nil {
		return zero, fmt.Errorf("service %q arg[%d]: %w", "product.handler", '\x01', err)
	}
	return app.NewProductHandler(dep_product_repo, dep_product_handler_logger), nil
}

func (c *Container) buildProductHandlerLogger() (*slog.Logger, error) {
	var zero *slog.Logger
	recv_product_handler_logger, err := c.getLogger()
	if err != nil {
		return zero, fmt.Errorf("service %q receiver %q: %w", "product.handler.logger", "logger", err)
	}
	return recv_product_handler_logger.With("channel", "product"), nil
}

func (c *Container) buildProductRepo() (app.ProductRepository, error) {
	var zero app.ProductRepository
	param_db_dsn, err := c.params.GetString("db_dsn")
	if err != nil {
		return zero, fmt.Errorf("service %q arg[%d] param %q: %w", "product.repo", '\x00', "db_dsn", err)
	}
	return app.NewProductRepository(param_db_dsn), nil
}

func (c *Container) buildServer() (*app.Server, error) {
	var zero *app.Server
	tag_product_handler, err := c.getProductHandler()
	if err != nil {
		return zero, fmt.Errorf("service %q arg[%d] tag %q: %w", "server", '\x00', "http.handler", err)
	}
	tag_user_handler, err := c.getUserHandler()
	if err != nil {
		return zero, fmt.Errorf("service %q arg[%d] tag %q: %w", "server", '\x00', "http.handler", err)
	}
	return app.NewServer([]app.HTTPHandler{tag_product_handler, tag_user_handler}), nil
}

func (c *Container) buildUserHandler() (app.HTTPHandler, error) {
	var zero app.HTTPHandler
	dep_user_repo, err := c.getUserRepo()
	if err != nil {
		return zero, fmt.Errorf("service %q arg[%d]: %w", "user.handler", '\x00', err)
	}
	dep_user_handler_logger, err := c.getUserHandlerLogger()
	if err != nil {
		return zero, fmt.Errorf("service %q arg[%d]: %w", "user.handler", '\x01', err)
	}
	return app.NewUserHandler(dep_user_repo, dep_user_handler_logger), nil
}

func (c *Container) buildUserHandlerLogger() (*slog.Logger, error) {
	var zero *slog.Logger
	recv_user_handler_logger, err := c.getLogger()
	if err != nil {
		return zero, fmt.Errorf("service %q receiver %q: %w", "user.handler.logger", "logger", err)
	}
	return recv_user_handler_logger.With("channel", "product"), nil
}

func (c *Container) buildUserRepo() (app.UserRepository, error) {
	var zero app.UserRepository
	param_db_dsn, err := c.params.GetString("db_dsn")
	if err != nil {
		return zero, fmt.Errorf("service %q arg[%d] param %q: %w", "user.repo", '\x00', "db_dsn", err)
	}
	return app.NewUserRepository(param_db_dsn), nil
}

func (c *Container) getLogger() (*slog.Logger, error) {
	var zero *slog.Logger
	if c.svc_logger != nil {
		return c.svc_logger, nil
	}
	res, err := c.buildLogger()
	if err != nil {
		return zero, err
	}
	c.svc_logger = res
	return res, nil
}

func (c *Container) getProductHandler() (app.HTTPHandler, error) {
	var zero app.HTTPHandler
	if c.svc_product_handlerInit {
		return c.svc_product_handler, nil
	}
	res, err := c.buildProductHandler()
	if err != nil {
		return zero, err
	}
	c.svc_product_handler = res
	c.svc_product_handlerInit = true
	return res, nil
}

func (c *Container) getProductHandlerLogger() (*slog.Logger, error) {
	var zero *slog.Logger
	if c.svc_product_handler_logger != nil {
		return c.svc_product_handler_logger, nil
	}
	res, err := c.buildProductHandlerLogger()
	if err != nil {
		return zero, err
	}
	c.svc_product_handler_logger = res
	return res, nil
}

func (c *Container) getProductRepo() (app.ProductRepository, error) {
	var zero app.ProductRepository
	if c.svc_product_repoInit {
		return c.svc_product_repo, nil
	}
	res, err := c.buildProductRepo()
	if err != nil {
		return zero, err
	}
	c.svc_product_repo = res
	c.svc_product_repoInit = true
	return res, nil
}

func (c *Container) getServer() (*app.Server, error) {
	var zero *app.Server
	if c.svc_server != nil {
		return c.svc_server, nil
	}
	res, err := c.buildServer()
	if err != nil {
		return zero, err
	}
	c.svc_server = res
	return res, nil
}

func (c *Container) getUserHandler() (app.HTTPHandler, error) {
	var zero app.HTTPHandler
	if c.svc_user_handlerInit {
		return c.svc_user_handler, nil
	}
	res, err := c.buildUserHandler()
	if err != nil {
		return zero, err
	}
	c.svc_user_handler = res
	c.svc_user_handlerInit = true
	return res, nil
}

func (c *Container) getUserHandlerLogger() (*slog.Logger, error) {
	var zero *slog.Logger
	if c.svc_user_handler_logger != nil {
		return c.svc_user_handler_logger, nil
	}
	res, err := c.buildUserHandlerLogger()
	if err != nil {
		return zero, err
	}
	c.svc_user_handler_logger = res
	return res, nil
}

func (c *Container) getUserRepo() (app.UserRepository, error) {
	var zero app.UserRepository
	if c.svc_user_repoInit {
		return c.svc_user_repo, nil
	}
	res, err := c.buildUserRepo()
	if err != nil {
		return zero, err
	}
	c.svc_user_repo = res
	c.svc_user_repoInit = true
	return res, nil
}

func (c *Container) GetProductHandler() (app.HTTPHandler, error) {
	c.mu.Lock()
	defer c.mu.Unlock()
	return c.getProductHandler()
}

func (c *Container) GetServer() (*app.Server, error) {
	c.mu.Lock()
	defer c.mu.Unlock()
	return c.getServer()
}
