// Code generated by gendi; DO NOT EDIT.
package main

import (
	"fmt"
	app "github.com/asp24/gendi/examples/custom-pass/internal/app"
	"github.com/asp24/gendi/parameters"
	stdlib "github.com/asp24/gendi/stdlib"
	io "io"
	slog "log/slog"
	"sync"
)

var DefaultContainerParameters = parameters.NewProviderMap(map[string]any{
	"db_dsn":            "postgres://localhost/myapp",
	"stdlib.slog.level": 0,
})

type Container struct {
	mu               sync.Mutex
	params           parameters.Provider
	onMustCallFailed func(serviceName string, err error)
	svc_stdlib_slog  *slog.Logger
	svc_server       *app.Server
}

type ContainerOption func(*Container)

func WithContainerErrorHandler(handler func(serviceName string, err error)) ContainerOption {
	return func(c *Container) {
		c.onMustCallFailed = handler
	}
}

func NewContainer(params parameters.Provider, opts ...ContainerOption) *Container {
	if params == nil {
		params = DefaultContainerParameters
	}
	c := &Container{
		params:           params,
		onMustCallFailed: func(string, error) {},
	}
	for _, opt := range opts {
		opt(c)
	}
	return c
}

func (c *Container) buildStdlibStderr() (io.Writer, error) {
	return stdlib.NewStderr(), nil
}

func (c *Container) buildStdlibSlogHandlerText() (slog.Handler, error) {
	var zero slog.Handler
	arg0_stdlib_slog_writer, err := c.getStdlibSlogWriter()
	if err != nil {
		return zero, fmt.Errorf("service %q arg[%d]: %w", "stdlib.slog.handler.text", '\x00', err)
	}
	param1_stdlib_slog_level, err := c.params.GetInt("stdlib.slog.level")
	if err != nil {
		return zero, fmt.Errorf("service %q arg[%d] param %q: %w", "stdlib.slog.handler.text", '\x01', "stdlib.slog.level", err)
	}
	return stdlib.NewSlogTextHandler(arg0_stdlib_slog_writer, slog.Level(param1_stdlib_slog_level)), nil
}

func (c *Container) buildStdlibSlog() (*slog.Logger, error) {
	var zero *slog.Logger
	arg0_stdlib_slog_handler, err := c.getStdlibSlogHandler()
	if err != nil {
		return zero, fmt.Errorf("service %q arg[%d]: %w", "stdlib.slog", '\x00', err)
	}
	return stdlib.NewSlogLogger(arg0_stdlib_slog_handler), nil
}

func (c *Container) buildProductHandlerLogger() (*slog.Logger, error) {
	var zero *slog.Logger
	recv_product_handler_logger, err := c.getLogger()
	if err != nil {
		return zero, fmt.Errorf("service %q receiver %q: %w", "product.handler.logger", "logger", err)
	}
	return recv_product_handler_logger.With("channel", "product"), nil
}

func (c *Container) buildProductRepo() (*app.ProductRepoImpl, error) {
	var zero *app.ProductRepoImpl
	param0_db_dsn, err := c.params.GetString("db_dsn")
	if err != nil {
		return zero, fmt.Errorf("service %q arg[%d] param %q: %w", "product.repo", '\x00', "db_dsn", err)
	}
	return app.NewProductRepository(param0_db_dsn), nil
}

func (c *Container) buildProductHandler() (app.HTTPHandler, error) {
	var zero app.HTTPHandler
	arg0_product_handler_logger, err := c.getProductHandlerLogger()
	if err != nil {
		return zero, fmt.Errorf("service %q arg[%d]: %w", "product.handler", '\x00', err)
	}
	arg1_product_repo, err := c.getProductRepo()
	if err != nil {
		return zero, fmt.Errorf("service %q arg[%d]: %w", "product.handler", '\x01', err)
	}
	return app.NewProductHandler(arg0_product_handler_logger, arg1_product_repo), nil
}

func (c *Container) buildUserHandlerLogger() (*slog.Logger, error) {
	var zero *slog.Logger
	recv_user_handler_logger, err := c.getLogger()
	if err != nil {
		return zero, fmt.Errorf("service %q receiver %q: %w", "user.handler.logger", "logger", err)
	}
	return recv_user_handler_logger.With("channel", "user"), nil
}

func (c *Container) buildUserRepo() (*app.UserRepoImpl, error) {
	var zero *app.UserRepoImpl
	param0_db_dsn, err := c.params.GetString("db_dsn")
	if err != nil {
		return zero, fmt.Errorf("service %q arg[%d] param %q: %w", "user.repo", '\x00', "db_dsn", err)
	}
	return app.NewUserRepository(param0_db_dsn), nil
}

func (c *Container) buildUserHandler() (app.HTTPHandler, error) {
	var zero app.HTTPHandler
	arg0_user_handler_logger, err := c.getUserHandlerLogger()
	if err != nil {
		return zero, fmt.Errorf("service %q arg[%d]: %w", "user.handler", '\x00', err)
	}
	arg1_user_repo, err := c.getUserRepo()
	if err != nil {
		return zero, fmt.Errorf("service %q arg[%d]: %w", "user.handler", '\x01', err)
	}
	return app.NewUserHandler(arg0_user_handler_logger, arg1_user_repo), nil
}

func (c *Container) buildTaggedWithHttpHandler() ([]app.HTTPHandler, error) {
	var zero []app.HTTPHandler
	arg0_product_handler, err := c.getProductHandler()
	if err != nil {
		return zero, fmt.Errorf("service %q arg[%d]: %w", "__tagged_with.http.handler", '\x00', err)
	}
	arg1_user_handler, err := c.getUserHandler()
	if err != nil {
		return zero, fmt.Errorf("service %q arg[%d]: %w", "__tagged_with.http.handler", '\x01', err)
	}
	return []app.HTTPHandler{arg0_product_handler, arg1_user_handler}, nil
}

func (c *Container) buildServerLogger() (*slog.Logger, error) {
	var zero *slog.Logger
	recv_server_logger, err := c.getLogger()
	if err != nil {
		return zero, fmt.Errorf("service %q receiver %q: %w", "server.logger", "logger", err)
	}
	return recv_server_logger.With("channel", "http"), nil
}

func (c *Container) buildServer() (*app.Server, error) {
	var zero *app.Server
	arg0_server_logger, err := c.getServerLogger()
	if err != nil {
		return zero, fmt.Errorf("service %q arg[%d]: %w", "server", '\x00', err)
	}
	arg1___tagged_with_http_handler, err := c.getTaggedWithHttpHandler()
	if err != nil {
		return zero, fmt.Errorf("service %q arg[%d]: %w", "server", '\x01', err)
	}
	return app.NewServer(arg0_server_logger, arg1___tagged_with_http_handler), nil
}

func (c *Container) getStdlibStderr() (io.Writer, error) {
	return c.buildStdlibStderr()
}

func (c *Container) getStdlibSlogWriter() (io.Writer, error) {
	return c.getStdlibStderr()
}

func (c *Container) getStdlibSlogHandlerText() (slog.Handler, error) {
	return c.buildStdlibSlogHandlerText()
}

func (c *Container) getStdlibSlogHandler() (slog.Handler, error) {
	return c.getStdlibSlogHandlerText()
}

func (c *Container) getStdlibSlog() (*slog.Logger, error) {
	if c.svc_stdlib_slog != nil {
		return c.svc_stdlib_slog, nil
	}
	res, err := c.buildStdlibSlog()
	if err != nil {
		return nil, err
	}
	c.svc_stdlib_slog = res
	return res, nil
}

func (c *Container) getLogger() (*slog.Logger, error) {
	return c.getStdlibSlog()
}

func (c *Container) getProductHandlerLogger() (*slog.Logger, error) {
	return c.buildProductHandlerLogger()
}

func (c *Container) getProductRepo() (*app.ProductRepoImpl, error) {
	return c.buildProductRepo()
}

func (c *Container) getProductHandler() (app.HTTPHandler, error) {
	return c.buildProductHandler()
}

func (c *Container) getUserHandlerLogger() (*slog.Logger, error) {
	return c.buildUserHandlerLogger()
}

func (c *Container) getUserRepo() (*app.UserRepoImpl, error) {
	return c.buildUserRepo()
}

func (c *Container) getUserHandler() (app.HTTPHandler, error) {
	return c.buildUserHandler()
}

func (c *Container) getTaggedWithHttpHandler() ([]app.HTTPHandler, error) {
	return c.buildTaggedWithHttpHandler()
}

func (c *Container) getServerLogger() (*slog.Logger, error) {
	return c.buildServerLogger()
}

func (c *Container) getServer() (*app.Server, error) {
	if c.svc_server != nil {
		return c.svc_server, nil
	}
	res, err := c.buildServer()
	if err != nil {
		return nil, err
	}
	c.svc_server = res
	return res, nil
}

func (c *Container) GetServer() (*app.Server, error) {
	c.mu.Lock()
	defer c.mu.Unlock()
	return c.getServer()
}

func (c *Container) MustServer() *app.Server {
	res, err := c.GetServer()
	if err != nil {
		c.onMustCallFailed("server", err)
		panic(err)
	}
	return res
}
