// Code generated by gendi; DO NOT EDIT.
package main

import (
	"sync"

	"github.com/asp24/gendi/parameters"
)

type Container struct {
	mu               sync.Mutex
	params           parameters.Provider
	onMustCallFailed func(serviceName string, err error)
	svc_server       *Server
}

type ContainerOption func(*Container)

func WithContainerErrorHandler(handler func(serviceName string, err error)) ContainerOption {
	return func(c *Container) {
		c.onMustCallFailed = handler
	}
}

func NewContainer(params parameters.Provider, opts ...ContainerOption) *Container {
	if params == nil {
		params = parameters.ProviderNullInstance
	}
	c := &Container{
		params:           params,
		onMustCallFailed: func(string, error) {},
	}
	for _, opt := range opts {
		opt(c)
	}
	return c
}

func (c *Container) buildServer() (*Server, error) {
	return NewServer(Defaults.Host, Defaults.Database.DSN), nil
}

func (c *Container) getServer() (*Server, error) {
	if c.svc_server != nil {
		return c.svc_server, nil
	}
	res, err := c.buildServer()
	if err != nil {
		return nil, err
	}
	c.svc_server = res
	return res, nil
}

func (c *Container) GetServer() (*Server, error) {
	c.mu.Lock()
	defer c.mu.Unlock()
	return c.getServer()
}

func (c *Container) MustServer() *Server {
	res, err := c.GetServer()
	if err != nil {
		c.onMustCallFailed("server", err)
		panic(err)
	}
	return res
}
