// Code generated by di-gen; DO NOT EDIT.
package di

import (
	"fmt"
	app "github.com/asp24/gendi/examples/advanced/app"
	"github.com/asp24/gendi/parameters"
	"sync"
)

var DefaultParameters = parameters.NewProviderMap(map[string]any{
	"dsn":          "postgres://localhost/advanced",
	"log_prefix":   "[us-east-1] ",
	"mail_host":    "smtp.us.example",
	"mail_prefix":  "ADV-",
	"mail_retries": 5,
})

type Container struct {
	mu                     sync.Mutex
	params                 parameters.Provider
	svc_db                 *app.DB
	svc_factory            *app.Factory
	svc_handler            *app.Handler
	svc_logger             *app.Logger
	svc_mailer             *app.MailerPrefixDecorator
	svc_notifier_aggregate *app.AggregateNotifier
}

func NewContainer(params parameters.Provider) *Container {
	if params == nil {
		params = DefaultParameters
	}
	return &Container{params: params}
}

func (c *Container) buildDb() (*app.DB, error) {
	var zero *app.DB
	param0_dsn, err := c.params.GetString("dsn")
	if err != nil {
		return zero, fmt.Errorf("service %q arg[%d] param %q: %w", "db", '\x00', "dsn", err)
	}
	res, err := app.NewDB(param0_dsn)
	if err != nil {
		return zero, fmt.Errorf("service %q constructor: %w", "db", err)
	}
	return res, nil
}

func (c *Container) buildFactory() (*app.Factory, error) {
	var zero *app.Factory
	arg0_logger, err := c.getLogger()
	if err != nil {
		return zero, fmt.Errorf("service %q arg[%d]: %w", "factory", '\x00', err)
	}
	return app.NewFactory(arg0_logger), nil
}

func (c *Container) buildHandler() (*app.Handler, error) {
	var zero *app.Handler
	arg0_db, err := c.getDb()
	if err != nil {
		return zero, fmt.Errorf("service %q arg[%d]: %w", "handler", '\x00', err)
	}
	arg1_notifier, err := c.getNotifier()
	if err != nil {
		return zero, fmt.Errorf("service %q arg[%d]: %w", "handler", '\x01', err)
	}
	recv_handler, err := c.getFactory()
	if err != nil {
		return zero, fmt.Errorf("service %q receiver %q: %w", "handler", "factory", err)
	}
	return recv_handler.NewHandler(arg0_db, arg1_notifier), nil
}

func (c *Container) buildLogger() (*app.Logger, error) {
	var zero *app.Logger
	param0_log_prefix, err := c.params.GetString("log_prefix")
	if err != nil {
		return zero, fmt.Errorf("service %q arg[%d] param %q: %w", "logger", '\x00', "log_prefix", err)
	}
	return app.NewLogger(param0_log_prefix), nil
}

func (c *Container) buildMailer() (app.Mailer, error) {
	var zero app.Mailer
	param0_mail_host, err := c.params.GetString("mail_host")
	if err != nil {
		return zero, fmt.Errorf("service %q arg[%d] param %q: %w", "mailer", '\x00', "mail_host", err)
	}
	return app.NewMailerBasic(param0_mail_host), nil
}

func (c *Container) buildMailerPrefixDecorator(inner app.Mailer) (*app.MailerPrefixDecorator, error) {
	var zero *app.MailerPrefixDecorator
	param1_mail_prefix, err := c.params.GetString("mail_prefix")
	if err != nil {
		return zero, fmt.Errorf("service %q arg[%d] param %q: %w", "mailer.prefix", '\x01', "mail_prefix", err)
	}
	return app.NewMailerPrefixDecorator(inner, param1_mail_prefix), nil
}

func (c *Container) buildMailerRetryDecorator(inner app.Mailer) (*app.MailerRetryDecorator, error) {
	var zero *app.MailerRetryDecorator
	param1_mail_retries, err := c.params.GetInt("mail_retries")
	if err != nil {
		return zero, fmt.Errorf("service %q arg[%d] param %q: %w", "mailer.retry", '\x01', "mail_retries", err)
	}
	return app.NewMailerRetryDecorator(inner, param1_mail_retries), nil
}

func (c *Container) buildNotifierAggregate() (*app.AggregateNotifier, error) {
	var zero *app.AggregateNotifier
	arg0_tagged_notifier, err := c.getTaggedWithNotifier()
	if err != nil {
		return zero, fmt.Errorf("service %q arg[%d] tag %q: %w", "notifier.aggregate", '\x00', "notifier", err)
	}
	return app.NewAggregateNotifier(arg0_tagged_notifier), nil
}

func (c *Container) buildNotifierEmail() (*app.EmailNotifier, error) {
	var zero *app.EmailNotifier
	arg0_mailer, err := c.getMailer()
	if err != nil {
		return zero, fmt.Errorf("service %q arg[%d]: %w", "notifier.email", '\x00', err)
	}
	return app.NewEmailNotifier(arg0_mailer), nil
}

func (c *Container) buildNotifierSms() (app.SMSNotifier, error) {
	return app.NewSMSNotifier(), nil
}

func (c *Container) buildDecoratedMailerPrefix() (*app.MailerPrefixDecorator, error) {
	var zero *app.MailerPrefixDecorator
	inner0, err := c.buildMailer()
	if err != nil {
		return zero, fmt.Errorf("service %q base %q: %w", "mailer.prefix", "mailer", err)
	}
	inner1, err := c.buildMailerRetryDecorator(inner0)
	if err != nil {
		return zero, fmt.Errorf("service %q decorator %q: %w", "mailer.prefix", "mailer.retry", err)
	}
	inner2, err := c.buildMailerPrefixDecorator(inner1)
	if err != nil {
		return zero, fmt.Errorf("service %q decorator %q: %w", "mailer.prefix", "mailer.prefix", err)
	}
	return inner2, nil
}

func (c *Container) buildDecoratedMailerRetry() (*app.MailerRetryDecorator, error) {
	var zero *app.MailerRetryDecorator
	inner0, err := c.buildMailer()
	if err != nil {
		return zero, fmt.Errorf("service %q base %q: %w", "mailer.retry", "mailer", err)
	}
	inner1, err := c.buildMailerRetryDecorator(inner0)
	if err != nil {
		return zero, fmt.Errorf("service %q decorator %q: %w", "mailer.retry", "mailer.retry", err)
	}
	return inner1, nil
}

func (c *Container) getDb() (*app.DB, error) {
	var zero *app.DB
	if c.svc_db != nil {
		return c.svc_db, nil
	}
	res, err := c.buildDb()
	if err != nil {
		return zero, err
	}
	c.svc_db = res
	return res, nil
}

func (c *Container) getFactory() (*app.Factory, error) {
	var zero *app.Factory
	if c.svc_factory != nil {
		return c.svc_factory, nil
	}
	res, err := c.buildFactory()
	if err != nil {
		return zero, err
	}
	c.svc_factory = res
	return res, nil
}

func (c *Container) getHandler() (*app.Handler, error) {
	var zero *app.Handler
	if c.svc_handler != nil {
		return c.svc_handler, nil
	}
	res, err := c.buildHandler()
	if err != nil {
		return zero, err
	}
	c.svc_handler = res
	return res, nil
}

func (c *Container) getLogger() (*app.Logger, error) {
	var zero *app.Logger
	if c.svc_logger != nil {
		return c.svc_logger, nil
	}
	res, err := c.buildLogger()
	if err != nil {
		return zero, err
	}
	c.svc_logger = res
	return res, nil
}

func (c *Container) getMailer() (*app.MailerPrefixDecorator, error) {
	var zero *app.MailerPrefixDecorator
	if c.svc_mailer != nil {
		return c.svc_mailer, nil
	}
	res, err := c.buildDecoratedMailerPrefix()
	if err != nil {
		return zero, err
	}
	c.svc_mailer = res
	return res, nil
}

func (c *Container) getNotifier() (*app.AggregateNotifier, error) {
	return c.getNotifierAggregate()
}

func (c *Container) getNotifierAggregate() (*app.AggregateNotifier, error) {
	var zero *app.AggregateNotifier
	if c.svc_notifier_aggregate != nil {
		return c.svc_notifier_aggregate, nil
	}
	res, err := c.buildNotifierAggregate()
	if err != nil {
		return zero, err
	}
	c.svc_notifier_aggregate = res
	return res, nil
}

func (c *Container) getNotifierEmail() (*app.EmailNotifier, error) {
	var zero *app.EmailNotifier
	res, err := c.buildNotifierEmail()
	if err != nil {
		return zero, err
	}
	return res, nil
}

func (c *Container) getNotifierSms() (app.SMSNotifier, error) {
	var zero app.SMSNotifier
	res, err := c.buildNotifierSms()
	if err != nil {
		return zero, err
	}
	return res, nil
}

func (c *Container) getTaggedWithNotifier() ([]app.Notifier, error) {
	items := make([]app.Notifier, 0, 2)
	tagged_notifier_email, err := c.getNotifierEmail()
	if err != nil {
		return nil, err
	}
	items = append(items, tagged_notifier_email)
	tagged_notifier_sms, err := c.getNotifierSms()
	if err != nil {
		return nil, err
	}
	items = append(items, tagged_notifier_sms)
	return items, nil
}

func (c *Container) GetHandler() (*app.Handler, error) {
	c.mu.Lock()
	defer c.mu.Unlock()
	return c.getHandler()
}

func (c *Container) GetTaggedWithNotifier() ([]app.Notifier, error) {
	c.mu.Lock()
	defer c.mu.Unlock()
	return c.getTaggedWithNotifier()
}
