// Code generated by di-gen; DO NOT EDIT.
package di

import (
	"fmt"
	app "github.com/asp24/gendi/examples/advanced/app"
	"github.com/asp24/gendi/parameters"
	"sync"
)

var DefaultParameters = parameters.NewProviderMap(map[string]any{
	"dsn":          "postgres://localhost/advanced",
	"log_prefix":   "[us-east-1] ",
	"mail_host":    "smtp.us.example",
	"mail_prefix":  "ADV-",
	"mail_retries": 5,
})

type Container struct {
	mu                     sync.Mutex
	params                 parameters.Provider
	svc_notifier_sms       *app.SMSNotifier
	svc_notifier_email     *app.EmailNotifier
	svc_notifier_aggregate *app.AggregateNotifier
	svc_handler            *app.Handler
}

func NewContainer(params parameters.Provider) *Container {
	if params == nil {
		params = DefaultParameters
	}
	return &Container{params: params}
}

func (c *Container) buildMailerRetryInner() (app.Mailer, error) {
	var zero app.Mailer
	param0_mail_host, err := c.params.GetString("mail_host")
	if err != nil {
		return zero, fmt.Errorf("service %q arg[%d] param %q: %w", "mailer.retry.inner", '\x00', "mail_host", err)
	}
	return app.NewMailerBasic(param0_mail_host), nil
}

func (c *Container) buildMailerRetry() (*app.MailerRetryDecorator, error) {
	var zero *app.MailerRetryDecorator
	arg0_mailer_retry_inner, err := c.getMailerRetryInner()
	if err != nil {
		return zero, fmt.Errorf("service %q arg[%d]: %w", "mailer.retry", '\x00', err)
	}
	param1_mail_retries, err := c.params.GetInt("mail_retries")
	if err != nil {
		return zero, fmt.Errorf("service %q arg[%d] param %q: %w", "mailer.retry", '\x01', "mail_retries", err)
	}
	return app.NewMailerRetryDecorator(arg0_mailer_retry_inner, param1_mail_retries), nil
}

func (c *Container) buildMailerPrefix() (*app.MailerPrefixDecorator, error) {
	var zero *app.MailerPrefixDecorator
	arg0_mailer_retry, err := c.getMailerRetry()
	if err != nil {
		return zero, fmt.Errorf("service %q arg[%d]: %w", "mailer.prefix", '\x00', err)
	}
	param1_mail_prefix, err := c.params.GetString("mail_prefix")
	if err != nil {
		return zero, fmt.Errorf("service %q arg[%d] param %q: %w", "mailer.prefix", '\x01', "mail_prefix", err)
	}
	return app.NewMailerPrefixDecorator(arg0_mailer_retry, param1_mail_prefix), nil
}

func (c *Container) buildNotifierSms() (*app.SMSNotifier, error) {
	return app.NewSMSNotifier(), nil
}

func (c *Container) buildNotifierEmail() (*app.EmailNotifier, error) {
	var zero *app.EmailNotifier
	arg0_mailer, err := c.getMailer()
	if err != nil {
		return zero, fmt.Errorf("service %q arg[%d]: %w", "notifier.email", '\x00', err)
	}
	return app.NewEmailNotifier(arg0_mailer), nil
}

func (c *Container) buildNotifierAggregate() (*app.AggregateNotifier, error) {
	var zero *app.AggregateNotifier
	arg0_tagged_notifier, err := c.getTaggedWithNotifier()
	if err != nil {
		return zero, fmt.Errorf("service %q arg[%d] tag %q: %w", "notifier.aggregate", '\x00', "notifier", err)
	}
	return app.NewAggregateNotifier(arg0_tagged_notifier), nil
}

func (c *Container) buildLogger() (*app.Logger, error) {
	var zero *app.Logger
	param0_log_prefix, err := c.params.GetString("log_prefix")
	if err != nil {
		return zero, fmt.Errorf("service %q arg[%d] param %q: %w", "logger", '\x00', "log_prefix", err)
	}
	return app.NewLogger(param0_log_prefix), nil
}

func (c *Container) buildFactory() (*app.Factory, error) {
	var zero *app.Factory
	arg0_logger, err := c.getLogger()
	if err != nil {
		return zero, fmt.Errorf("service %q arg[%d]: %w", "factory", '\x00', err)
	}
	return app.NewFactory(arg0_logger), nil
}

func (c *Container) buildDb() (*app.DB, error) {
	var zero *app.DB
	param0_dsn, err := c.params.GetString("dsn")
	if err != nil {
		return zero, fmt.Errorf("service %q arg[%d] param %q: %w", "db", '\x00', "dsn", err)
	}
	res, err := app.NewDB(param0_dsn)
	if err != nil {
		return zero, fmt.Errorf("service %q constructor: %w", "db", err)
	}
	return res, nil
}

func (c *Container) buildHandler() (*app.Handler, error) {
	var zero *app.Handler
	arg0_db, err := c.getDb()
	if err != nil {
		return zero, fmt.Errorf("service %q arg[%d]: %w", "handler", '\x00', err)
	}
	arg1_notifier, err := c.getNotifier()
	if err != nil {
		return zero, fmt.Errorf("service %q arg[%d]: %w", "handler", '\x01', err)
	}
	recv_handler, err := c.getFactory()
	if err != nil {
		return zero, fmt.Errorf("service %q receiver %q: %w", "handler", "factory", err)
	}
	return recv_handler.NewHandler(arg0_db, arg1_notifier), nil
}

func (c *Container) getMailerRetryInner() (app.Mailer, error) {
	var zero app.Mailer
	res, err := c.buildMailerRetryInner()
	if err != nil {
		return zero, err
	}
	return res, nil
}

func (c *Container) getMailerRetry() (*app.MailerRetryDecorator, error) {
	var zero *app.MailerRetryDecorator
	res, err := c.buildMailerRetry()
	if err != nil {
		return zero, err
	}
	return res, nil
}

func (c *Container) getMailerPrefix() (*app.MailerPrefixDecorator, error) {
	var zero *app.MailerPrefixDecorator
	res, err := c.buildMailerPrefix()
	if err != nil {
		return zero, err
	}
	return res, nil
}

func (c *Container) getMailer() (*app.MailerPrefixDecorator, error) {
	return c.getMailerPrefix()
}

func (c *Container) getNotifierSms() (*app.SMSNotifier, error) {
	var zero *app.SMSNotifier
	if c.svc_notifier_sms != nil {
		return c.svc_notifier_sms, nil
	}
	res, err := c.buildNotifierSms()
	if err != nil {
		return zero, err
	}
	c.svc_notifier_sms = res
	return res, nil
}

func (c *Container) getNotifierEmail() (*app.EmailNotifier, error) {
	var zero *app.EmailNotifier
	if c.svc_notifier_email != nil {
		return c.svc_notifier_email, nil
	}
	res, err := c.buildNotifierEmail()
	if err != nil {
		return zero, err
	}
	c.svc_notifier_email = res
	return res, nil
}

func (c *Container) getNotifierAggregate() (*app.AggregateNotifier, error) {
	var zero *app.AggregateNotifier
	if c.svc_notifier_aggregate != nil {
		return c.svc_notifier_aggregate, nil
	}
	res, err := c.buildNotifierAggregate()
	if err != nil {
		return zero, err
	}
	c.svc_notifier_aggregate = res
	return res, nil
}

func (c *Container) getNotifier() (*app.AggregateNotifier, error) {
	return c.getNotifierAggregate()
}

func (c *Container) getLogger() (*app.Logger, error) {
	var zero *app.Logger
	res, err := c.buildLogger()
	if err != nil {
		return zero, err
	}
	return res, nil
}

func (c *Container) getFactory() (*app.Factory, error) {
	var zero *app.Factory
	res, err := c.buildFactory()
	if err != nil {
		return zero, err
	}
	return res, nil
}

func (c *Container) getDb() (*app.DB, error) {
	var zero *app.DB
	res, err := c.buildDb()
	if err != nil {
		return zero, err
	}
	return res, nil
}

func (c *Container) getHandler() (*app.Handler, error) {
	var zero *app.Handler
	if c.svc_handler != nil {
		return c.svc_handler, nil
	}
	res, err := c.buildHandler()
	if err != nil {
		return zero, err
	}
	c.svc_handler = res
	return res, nil
}

func (c *Container) getTaggedWithNotifier() ([]app.Notifier, error) {
	items := make([]app.Notifier, 0, 2)
	tagged_notifier_email, err := c.getNotifierEmail()
	if err != nil {
		return nil, err
	}
	items = append(items, tagged_notifier_email)
	tagged_notifier_sms, err := c.getNotifierSms()
	if err != nil {
		return nil, err
	}
	items = append(items, tagged_notifier_sms)
	return items, nil
}

func (c *Container) GetHandler() (*app.Handler, error) {
	c.mu.Lock()
	defer c.mu.Unlock()
	return c.getHandler()
}

func (c *Container) GetTaggedWithNotifier() ([]app.Notifier, error) {
	c.mu.Lock()
	defer c.mu.Unlock()
	return c.getTaggedWithNotifier()
}
