// Code generated by gendi; DO NOT EDIT.
package di

import (
	"fmt"
	app "github.com/asp24/gendi/examples/custom-pass/internal/app"
	"github.com/asp24/gendi/parameters"
	stdlib "github.com/asp24/gendi/stdlib"
	io "io"
	slog "log/slog"
	"sync"
)

var DefaultParameters = parameters.NewProviderMap(map[string]any{
	"db_dsn":                              "postgres://localhost/myapp",
	"stdlib.http.idle_conn_timeout":       "90s",
	"stdlib.http.max_idle_conns":          100,
	"stdlib.http.max_idle_conns_per_host": 10,
	"stdlib.http.timeout":                 "30s",
	"stdlib.slog.level":                   0,
})

type Container struct {
	mu                           sync.Mutex
	params                       parameters.Provider
	onMustCallFailed             func(serviceName string, err error)
	svc_stdlib_slog_handler_text slog.Handler
	svc_stdlib_slog              *slog.Logger
	svc_server                   *app.Server
}

type ContainerOption func(*Container)

func WithErrorHandler(handler func(serviceName string, err error)) ContainerOption {
	return func(c *Container) {
		c.onMustCallFailed = handler
	}
}

func NewContainer(params parameters.Provider, opts ...ContainerOption) *Container {
	if params == nil {
		params = DefaultParameters
	}
	c := &Container{
		params:           params,
		onMustCallFailed: func(string, error) {},
	}
	for _, opt := range opts {
		opt(c)
	}
	return c
}

func (c *Container) buildTaggedWithHttpHandler() ([]app.HTTPHandler, error) {
	return stdlib.MakeSlice[app.HTTPHandler](), nil
}

func (c *Container) buildStdlibStderr() (io.Writer, error) {
	return stdlib.NewStderr(), nil
}

func (c *Container) buildStdlibSlogHandlerText() (slog.Handler, error) {
	var zero slog.Handler
	arg0_stdlib_slog_writer, err := c.getStdlibSlogWriter()
	if err != nil {
		return zero, fmt.Errorf("service %q arg[%d]: %w", "stdlib.slog.handler.text", '\x00', err)
	}
	param1_stdlib_slog_level, err := c.params.GetInt("stdlib.slog.level")
	if err != nil {
		return zero, fmt.Errorf("service %q arg[%d] param %q: %w", "stdlib.slog.handler.text", '\x01', "stdlib.slog.level", err)
	}
	return stdlib.NewSlogTextHandler(arg0_stdlib_slog_writer, slog.Level(param1_stdlib_slog_level)), nil
}

func (c *Container) buildStdlibSlog() (*slog.Logger, error) {
	var zero *slog.Logger
	arg0_stdlib_slog_handler, err := c.getStdlibSlogHandler()
	if err != nil {
		return zero, fmt.Errorf("service %q arg[%d]: %w", "stdlib.slog", '\x00', err)
	}
	return stdlib.NewSlogLogger(arg0_stdlib_slog_handler), nil
}

func (c *Container) buildServer() (*app.Server, error) {
	var zero *app.Server
	arg0_logger, err := c.getLogger()
	if err != nil {
		return zero, fmt.Errorf("service %q arg[%d]: %w", "server", '\x00', err)
	}
	arg1___tagged_with_http_handler, err := c.getTaggedWithHttpHandler()
	if err != nil {
		return zero, fmt.Errorf("service %q arg[%d]: %w", "server", '\x01', err)
	}
	return app.NewServer(arg0_logger, arg1___tagged_with_http_handler), nil
}

func (c *Container) getTaggedWithHttpHandler() ([]app.HTTPHandler, error) {
	var zero []app.HTTPHandler
	res, err := c.buildTaggedWithHttpHandler()
	if err != nil {
		return zero, err
	}
	return res, nil
}

func (c *Container) getStdlibStderr() (io.Writer, error) {
	var zero io.Writer
	res, err := c.buildStdlibStderr()
	if err != nil {
		return zero, err
	}
	return res, nil
}

func (c *Container) getStdlibSlogWriter() (io.Writer, error) {
	return c.getStdlibStderr()
}

func (c *Container) getStdlibSlogHandlerText() (slog.Handler, error) {
	var zero slog.Handler
	if c.svc_stdlib_slog_handler_text != nil {
		return c.svc_stdlib_slog_handler_text, nil
	}
	res, err := c.buildStdlibSlogHandlerText()
	if err != nil {
		return zero, err
	}
	c.svc_stdlib_slog_handler_text = res
	return res, nil
}

func (c *Container) getStdlibSlogHandler() (slog.Handler, error) {
	return c.getStdlibSlogHandlerText()
}

func (c *Container) getStdlibSlog() (*slog.Logger, error) {
	var zero *slog.Logger
	if c.svc_stdlib_slog != nil {
		return c.svc_stdlib_slog, nil
	}
	res, err := c.buildStdlibSlog()
	if err != nil {
		return zero, err
	}
	c.svc_stdlib_slog = res
	return res, nil
}

func (c *Container) getLogger() (*slog.Logger, error) {
	return c.getStdlibSlog()
}

func (c *Container) getServer() (*app.Server, error) {
	var zero *app.Server
	if c.svc_server != nil {
		return c.svc_server, nil
	}
	res, err := c.buildServer()
	if err != nil {
		return zero, err
	}
	c.svc_server = res
	return res, nil
}

func (c *Container) GetServer() (*app.Server, error) {
	c.mu.Lock()
	defer c.mu.Unlock()
	return c.getServer()
}

func (c *Container) MustServer() *app.Server {
	res, err := c.GetServer()
	if err != nil {
		c.onMustCallFailed("server", err)
		panic(err)
	}
	return res
}
