// Code generated by gendi; DO NOT EDIT.
package di

import (
	"fmt"
	app "github.com/asp24/gendi/examples/decorator/app"
	"github.com/asp24/gendi/parameters"
	"sync"
)

type Container struct {
	mu                                   sync.Mutex
	params                               parameters.Provider
	onMustCallFailed                     func(serviceName string, err error)
	svc_payment_provider_with_comission  *app.PaymentProviderCommissionDecorator
	svc_payment_provider_with_comission2 *app.PaymentProviderCommissionDecorator
}

type ContainerOption func(*Container)

func WithErrorHandler(handler func(serviceName string, err error)) ContainerOption {
	return func(c *Container) {
		c.onMustCallFailed = handler
	}
}

func NewContainer(params parameters.Provider, opts ...ContainerOption) *Container {
	if params == nil {
		params = parameters.ProviderNullInstance
	}
	c := &Container{
		params:           params,
		onMustCallFailed: func(string, error) {},
	}
	for _, opt := range opts {
		opt(c)
	}
	return c
}

func (c *Container) buildPaymentProviderDummy() (*app.PaymentProviderDummy, error) {
	return app.NewPaymentProviderDummy(), nil
}

func (c *Container) buildPaymentProviderWithComission() (*app.PaymentProviderCommissionDecorator, error) {
	var zero *app.PaymentProviderCommissionDecorator
	arg0_payment_provider_dummy, err := c.getPaymentProviderDummy()
	if err != nil {
		return zero, fmt.Errorf("service %q arg[%d]: %w", "payment.provider_with_comission", '\x00', err)
	}
	return app.NewPaymentProviderCommissionDecorator(arg0_payment_provider_dummy, 1), nil
}

func (c *Container) buildPaymentProviderWithComission2() (*app.PaymentProviderCommissionDecorator, error) {
	var zero *app.PaymentProviderCommissionDecorator
	arg0_payment_provider_with_comission, err := c.getPaymentProviderWithComission()
	if err != nil {
		return zero, fmt.Errorf("service %q arg[%d]: %w", "payment.provider_with_comission2", '\x00', err)
	}
	return app.NewPaymentProviderCommissionDecorator(arg0_payment_provider_with_comission, 2), nil
}

func (c *Container) buildTaggedWithJob() ([]app.Job, error) {
	var zero []app.Job
	arg0_payment_provider_with_comission, err := c.getPaymentProviderWithComission()
	if err != nil {
		return zero, fmt.Errorf("service %q arg[%d]: %w", "__tagged_with.job", '\x00', err)
	}
	arg1_payment_provider_with_comission2, err := c.getPaymentProviderWithComission2()
	if err != nil {
		return zero, fmt.Errorf("service %q arg[%d]: %w", "__tagged_with.job", '\x01', err)
	}
	return []app.Job{arg0_payment_provider_with_comission, arg1_payment_provider_with_comission2}, nil
}

func (c *Container) getPaymentProviderDummy() (*app.PaymentProviderDummy, error) {
	return c.buildPaymentProviderDummy()
}

func (c *Container) getPaymentProviderWithComission() (*app.PaymentProviderCommissionDecorator, error) {
	if c.svc_payment_provider_with_comission != nil {
		return c.svc_payment_provider_with_comission, nil
	}
	res, err := c.buildPaymentProviderWithComission()
	if err != nil {
		return nil, err
	}
	c.svc_payment_provider_with_comission = res
	return res, nil
}

func (c *Container) getPaymentProviderWithComission2() (*app.PaymentProviderCommissionDecorator, error) {
	if c.svc_payment_provider_with_comission2 != nil {
		return c.svc_payment_provider_with_comission2, nil
	}
	res, err := c.buildPaymentProviderWithComission2()
	if err != nil {
		return nil, err
	}
	c.svc_payment_provider_with_comission2 = res
	return res, nil
}

func (c *Container) getTaggedWithJob() ([]app.Job, error) {
	return c.buildTaggedWithJob()
}

func (c *Container) getPaymentProvider() (*app.PaymentProviderCommissionDecorator, error) {
	return c.getPaymentProviderWithComission2()
}

func (c *Container) GetTaggedWithJob() ([]app.Job, error) {
	c.mu.Lock()
	defer c.mu.Unlock()
	return c.getTaggedWithJob()
}

func (c *Container) MustTaggedWithJob() []app.Job {
	res, err := c.GetTaggedWithJob()
	if err != nil {
		c.onMustCallFailed("__tagged_with.job", err)
		panic(err)
	}
	return res
}

func (c *Container) GetPaymentProvider() (*app.PaymentProviderCommissionDecorator, error) {
	c.mu.Lock()
	defer c.mu.Unlock()
	return c.getPaymentProvider()
}

func (c *Container) MustPaymentProvider() *app.PaymentProviderCommissionDecorator {
	res, err := c.GetPaymentProvider()
	if err != nil {
		c.onMustCallFailed("payment.provider", err)
		panic(err)
	}
	return res
}
