// Code generated by di-gen; DO NOT EDIT.
package di

import (
	"fmt"
	app "github.com/asp24/gendi/examples/decorator/app"
	"sync"
)

type Container struct {
	mu                         sync.Mutex
	svc_payment_provider       *app.PaymentProviderCommissionDecorator
	svc_payment_provider_dummy *app.PaymentProviderDummy
}

func (c *Container) buildPaymentProviderDummy() (*app.PaymentProviderDummy, error) {
	return app.NewPaymentProviderDummy(), nil
}

func (c *Container) buildPaymentProviderWithComissionDecorator(inner *app.PaymentProviderDummy) (*app.PaymentProviderCommissionDecorator, error) {
	return app.NewPaymentProviderCommissionDecorator(inner, 1), nil
}

func (c *Container) buildDecoratedPaymentProviderWithComission() (*app.PaymentProviderCommissionDecorator, error) {
	var zero *app.PaymentProviderCommissionDecorator
	inner0, err := c.buildPaymentProviderDummy()
	if err != nil {
		return zero, fmt.Errorf("service %q base %q: %w", "payment.provider_with_comission", "payment.provider", err)
	}
	inner1, err := c.buildPaymentProviderWithComissionDecorator(inner0)
	if err != nil {
		return zero, fmt.Errorf("service %q decorator %q: %w", "payment.provider_with_comission", "payment.provider_with_comission", err)
	}
	return inner1, nil
}

func (c *Container) getPaymentProvider() (*app.PaymentProviderCommissionDecorator, error) {
	var zero *app.PaymentProviderCommissionDecorator
	if c.svc_payment_provider != nil {
		return c.svc_payment_provider, nil
	}
	res, err := c.buildDecoratedPaymentProviderWithComission()
	if err != nil {
		return zero, err
	}
	c.svc_payment_provider = res
	return res, nil
}

func (c *Container) getPaymentProviderDummy() (*app.PaymentProviderDummy, error) {
	var zero *app.PaymentProviderDummy
	if c.svc_payment_provider_dummy != nil {
		return c.svc_payment_provider_dummy, nil
	}
	res, err := c.buildPaymentProviderDummy()
	if err != nil {
		return zero, err
	}
	c.svc_payment_provider_dummy = res
	return res, nil
}

func (c *Container) getPaymentProviderWithComission() (*app.PaymentProviderCommissionDecorator, error) {
	return c.getPaymentProvider()
}

func (c *Container) getTaggedWithJob() ([]app.Job, error) {
	items := make([]app.Job, 0, 1)
	tagged_payment_provider_with_comission, err := c.getPaymentProviderWithComission()
	if err != nil {
		return nil, err
	}
	items = append(items, tagged_payment_provider_with_comission)
	return items, nil
}

func (c *Container) GetPaymentProvider() (*app.PaymentProviderCommissionDecorator, error) {
	c.mu.Lock()
	defer c.mu.Unlock()
	return c.getPaymentProvider()
}

func (c *Container) GetTaggedWithJob() ([]app.Job, error) {
	c.mu.Lock()
	defer c.mu.Unlock()
	return c.getTaggedWithJob()
}
