// Code generated by di-gen; DO NOT EDIT.
package di

import (
	"fmt"
	app "github.com/asp24/gendi/examples/decorator/app"
	"sync"
)

type Container struct {
	mu                                   sync.Mutex
	svc_payment_provider_with_comission  *app.PaymentProviderCommissionDecorator
	svc_payment_provider_with_comission2 *app.PaymentProviderCommissionDecorator
}

func (c *Container) buildPaymentProviderDummy() (*app.PaymentProviderDummy, error) {
	return app.NewPaymentProviderDummy(), nil
}

func (c *Container) buildPaymentProviderWithComission() (*app.PaymentProviderCommissionDecorator, error) {
	var zero *app.PaymentProviderCommissionDecorator
	arg0_payment_provider_dummy, err := c.getPaymentProviderDummy()
	if err != nil {
		return zero, fmt.Errorf("service %q arg[%d]: %w", "payment.provider_with_comission", '\x00', err)
	}
	return app.NewPaymentProviderCommissionDecorator(arg0_payment_provider_dummy, 1), nil
}

func (c *Container) buildPaymentProviderWithComission2() (*app.PaymentProviderCommissionDecorator, error) {
	var zero *app.PaymentProviderCommissionDecorator
	arg0_payment_provider_with_comission, err := c.getPaymentProviderWithComission()
	if err != nil {
		return zero, fmt.Errorf("service %q arg[%d]: %w", "payment.provider_with_comission2", '\x00', err)
	}
	return app.NewPaymentProviderCommissionDecorator(arg0_payment_provider_with_comission, 2), nil
}

func (c *Container) getPaymentProviderDummy() (*app.PaymentProviderDummy, error) {
	var zero *app.PaymentProviderDummy
	res, err := c.buildPaymentProviderDummy()
	if err != nil {
		return zero, err
	}
	return res, nil
}

func (c *Container) getPaymentProviderWithComission() (*app.PaymentProviderCommissionDecorator, error) {
	var zero *app.PaymentProviderCommissionDecorator
	if c.svc_payment_provider_with_comission != nil {
		return c.svc_payment_provider_with_comission, nil
	}
	res, err := c.buildPaymentProviderWithComission()
	if err != nil {
		return zero, err
	}
	c.svc_payment_provider_with_comission = res
	return res, nil
}

func (c *Container) getPaymentProviderWithComission2() (*app.PaymentProviderCommissionDecorator, error) {
	var zero *app.PaymentProviderCommissionDecorator
	if c.svc_payment_provider_with_comission2 != nil {
		return c.svc_payment_provider_with_comission2, nil
	}
	res, err := c.buildPaymentProviderWithComission2()
	if err != nil {
		return zero, err
	}
	c.svc_payment_provider_with_comission2 = res
	return res, nil
}

func (c *Container) getPaymentProvider() (*app.PaymentProviderCommissionDecorator, error) {
	return c.getPaymentProviderWithComission2()
}

func (c *Container) getTaggedWithJob() ([]app.Job, error) {
	items := make([]app.Job, 0, 2)
	tagged_payment_provider_with_comission, err := c.getPaymentProviderWithComission()
	if err != nil {
		return nil, err
	}
	items = append(items, tagged_payment_provider_with_comission)
	tagged_payment_provider_with_comission2, err := c.getPaymentProviderWithComission2()
	if err != nil {
		return nil, err
	}
	items = append(items, tagged_payment_provider_with_comission2)
	return items, nil
}

func (c *Container) GetPaymentProvider() (*app.PaymentProviderCommissionDecorator, error) {
	c.mu.Lock()
	defer c.mu.Unlock()
	return c.getPaymentProvider()
}

func (c *Container) GetTaggedWithJob() ([]app.Job, error) {
	c.mu.Lock()
	defer c.mu.Unlock()
	return c.getTaggedWithJob()
}
