// Code generated by di-gen; DO NOT EDIT.
package di

import (
	"fmt"
	app "github.com/asp24/gendi/examples/basic/app"
	"github.com/asp24/gendi/parameters"
	"sync"
)

var DefaultParameters = parameters.NewProviderMap(map[string]any{
	"dsn":        "postgres://localhost/app",
	"log_prefix": "[app] ",
})

type Container struct {
	mu                          sync.Mutex
	params                      parameters.Provider
	svc_logger                  *app.Logger
	svc_provider_paypal         *app.PaymentProvider
	svc_provider_stripe         *app.PaymentProvider
	svc_service_decorator_inner *app.Service
	svc_timer                   *app.Timer
}

func NewContainer(params parameters.Provider) *Container {
	if params == nil {
		params = DefaultParameters
	}
	return &Container{params: params}
}

func (c *Container) buildLogger() (*app.Logger, error) {
	return app.NewLogger("[app] "), nil
}

func (c *Container) buildProviderPaypal() (*app.PaymentProvider, error) {
	return app.NewPaypalProvider(), nil
}

func (c *Container) buildProviderStripe() (*app.PaymentProvider, error) {
	return app.NewStripeProvider(), nil
}

func (c *Container) buildRepo() (*app.Repo, error) {
	var zero *app.Repo
	param0_dsn, err := c.params.GetString("dsn")
	if err != nil {
		return zero, fmt.Errorf("service %q arg[%d] param %q: %w", "repo", '\x00', "dsn", err)
	}
	return app.NewRepo(param0_dsn), nil
}

func (c *Container) buildServiceDecorator() (*app.Service, error) {
	var zero *app.Service
	arg0_service_decorator_inner, err := c.getServiceDecoratorInner()
	if err != nil {
		return zero, fmt.Errorf("service %q arg[%d]: %w", "service.decorator", '\x00', err)
	}
	arg1_logger, err := c.getLogger()
	if err != nil {
		return zero, fmt.Errorf("service %q arg[%d]: %w", "service.decorator", '\x01', err)
	}
	return app.DecorateService(arg0_service_decorator_inner, arg1_logger), nil
}

func (c *Container) buildServiceDecoratorInner() (*app.Service, error) {
	var zero *app.Service
	arg0_repo, err := c.getRepo()
	if err != nil {
		return zero, fmt.Errorf("service %q arg[%d]: %w", "service.decorator.inner", '\x00', err)
	}
	arg1_logger, err := c.getLogger()
	if err != nil {
		return zero, fmt.Errorf("service %q arg[%d]: %w", "service.decorator.inner", '\x01', err)
	}
	arg2_tagged_payment_provider, err := c.getTaggedWithPaymentProvider()
	if err != nil {
		return zero, fmt.Errorf("service %q arg[%d] tag %q: %w", "service.decorator.inner", '\x02', "payment.provider", err)
	}
	res, err := app.NewService(arg0_repo, arg1_logger, arg2_tagged_payment_provider)
	if err != nil {
		return zero, fmt.Errorf("service %q constructor: %w", "service.decorator.inner", err)
	}
	return res, nil
}

func (c *Container) buildTimer() (*app.Timer, error) {
	return app.NewTimer(1000000000), nil
}

func (c *Container) getLogger() (*app.Logger, error) {
	var zero *app.Logger
	if c.svc_logger != nil {
		return c.svc_logger, nil
	}
	res, err := c.buildLogger()
	if err != nil {
		return zero, err
	}
	c.svc_logger = res
	return res, nil
}

func (c *Container) getProviderPaypal() (*app.PaymentProvider, error) {
	var zero *app.PaymentProvider
	if c.svc_provider_paypal != nil {
		return c.svc_provider_paypal, nil
	}
	res, err := c.buildProviderPaypal()
	if err != nil {
		return zero, err
	}
	c.svc_provider_paypal = res
	return res, nil
}

func (c *Container) getProviderStripe() (*app.PaymentProvider, error) {
	var zero *app.PaymentProvider
	if c.svc_provider_stripe != nil {
		return c.svc_provider_stripe, nil
	}
	res, err := c.buildProviderStripe()
	if err != nil {
		return zero, err
	}
	c.svc_provider_stripe = res
	return res, nil
}

func (c *Container) getRepo() (*app.Repo, error) {
	var zero *app.Repo
	res, err := c.buildRepo()
	if err != nil {
		return zero, err
	}
	return res, nil
}

func (c *Container) getService() (*app.Service, error) {
	return c.getServiceDecorator()
}

func (c *Container) getServiceDecorator() (*app.Service, error) {
	var zero *app.Service
	res, err := c.buildServiceDecorator()
	if err != nil {
		return zero, err
	}
	return res, nil
}

func (c *Container) getServiceDecoratorInner() (*app.Service, error) {
	var zero *app.Service
	if c.svc_service_decorator_inner != nil {
		return c.svc_service_decorator_inner, nil
	}
	res, err := c.buildServiceDecoratorInner()
	if err != nil {
		return zero, err
	}
	c.svc_service_decorator_inner = res
	return res, nil
}

func (c *Container) getTimer() (*app.Timer, error) {
	var zero *app.Timer
	if c.svc_timer != nil {
		return c.svc_timer, nil
	}
	res, err := c.buildTimer()
	if err != nil {
		return zero, err
	}
	c.svc_timer = res
	return res, nil
}

func (c *Container) getTaggedWithPaymentProvider() ([]*app.PaymentProvider, error) {
	items := make([]*app.PaymentProvider, 0, 2)
	tagged_provider_stripe, err := c.getProviderStripe()
	if err != nil {
		return nil, err
	}
	items = append(items, tagged_provider_stripe)
	tagged_provider_paypal, err := c.getProviderPaypal()
	if err != nil {
		return nil, err
	}
	items = append(items, tagged_provider_paypal)
	return items, nil
}

func (c *Container) GetService() (*app.Service, error) {
	c.mu.Lock()
	defer c.mu.Unlock()
	return c.getService()
}

func (c *Container) GetServiceDecoratorInner() (*app.Service, error) {
	c.mu.Lock()
	defer c.mu.Unlock()
	return c.getServiceDecoratorInner()
}

func (c *Container) GetTimer() (*app.Timer, error) {
	c.mu.Lock()
	defer c.mu.Unlock()
	return c.getTimer()
}
